//! Embed `std/` in the module, because a browser tab has no filesystem to read
//! it from.
//!
//! This was not here at first, and the playground refused every `import` with the
//! loader's own `std library not available`. Then the guide book landed with a
//! run link on every chapter, and twenty of its twenty-five programs import
//! `std/strings`, `std/arrays`, `std/html` and six more. A playground the book
//! links to has to load what the book uses.
//!
//! The WHOLE directory, walked at build time rather than listed by hand: a list
//! would be one more place to forget a module, and the loader reads only the
//! modules a program actually imports, so the cost of the rest is bytes and not
//! behaviour.

use std::path::Path;

fn main() {
    let std_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../std");
    println!("cargo:rerun-if-changed={}", std_dir.display());

    let mut names: Vec<String> = std::fs::read_dir(&std_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", std_dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".vyrn"))
        .collect();
    // Sorted so the generated file is byte-identical between builds; a directory
    // listing is not ordered.
    names.sort();
    assert!(!names.is_empty(), "no std modules in {}", std_dir.display());

    let mut out = String::from(
        "// Generated by build.rs. The standard library, keyed the way the loader\n\
         // spells it against a `std_root` of `std`.\n\
         pub static STD: &[(&str, &str)] = &[\n",
    );
    for name in &names {
        let path = std_dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        out.push_str(&format!(
            "    (\"std/{name}\", include_str!(r\"{}\")),\n",
            path.display()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("std_modules.rs");
    std::fs::write(&dest, out).unwrap();
}
