/* Automatically generated by wasm2c */
#include <assert.h>
#include <math.h>
#include <stdarg.h>
#include <stddef.h>
#include <string.h>
#if defined(__MINGW32__)
#include <malloc.h>
#elif defined(_MSC_VER)
#include <intrin.h>
#include <malloc.h>
#define alloca _alloca
#elif defined(__FreeBSD__) || defined(__OpenBSD__)
#include <stdlib.h>
#else
#include <alloca.h>
#endif

#include "vyrn_listdir_22040.w2c.h"
#define IS_SINGLE_UNSHARED_MEMORY 1

// Computes a pointer to an object of the given size in a little-endian memory.
//
// On a little-endian host, this is just &mem->data[addr] - the object's size is
// unused. On a big-endian host, it's &mem->data[mem->size - addr - n], where n
// is the object's size.
//
// Note that mem may be evaluated multiple times.
//
// Parameters:
// mem - The memory.
// addr - The address.
// n - The size of the object.
//
// Result:
// A pointer for an object of size n.
#if WABT_BIG_ENDIAN
#define MEM_ADDR(mem, addr, n) ((mem)->data_end - (addr) - (n))
#else
#define MEM_ADDR(mem, addr, n) &((mem)->data[addr])
#endif

// We can only use Segue for this module if it uses a single unshared imported
// or exported memory
#if WASM_RT_USE_SEGUE && IS_SINGLE_UNSHARED_MEMORY
#define WASM_RT_USE_SEGUE_FOR_THIS_MODULE 1
#else
#define WASM_RT_USE_SEGUE_FOR_THIS_MODULE 0
#endif

#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
// POSIX uses FS for TLS, GS is free
static inline void* wasm_rt_segue_read_base() {
  if (wasm_rt_fsgsbase_inst_supported) {
    return (void*)__builtin_ia32_rdgsbase64();
  } else {
    return wasm_rt_syscall_get_segue_base();
  }
}
static inline void wasm_rt_segue_write_base(void* base) {
#if WASM_RT_SEGUE_FREE_SEGMENT
  if (wasm_rt_last_segment_val == base) {
    return;
  }

  wasm_rt_last_segment_val = base;
#endif

  if (wasm_rt_fsgsbase_inst_supported) {
    __builtin_ia32_wrgsbase64((uintptr_t)base);
  } else {
    wasm_rt_syscall_set_segue_base(base);
  }
}
#define MEM_ADDR_MEMOP(mem, addr, n) ((uint8_t __seg_gs*)(uintptr_t)addr)
#else
#define MEM_ADDR_MEMOP(mem, addr, n) MEM_ADDR(mem, addr, n)
#endif

#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)

#if WASM_RT_STACK_DEPTH_COUNT
#define FUNC_PROLOGUE                                            \
  if (++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) \
    TRAP(EXHAUSTION);

#define FUNC_EPILOGUE --wasm_rt_call_stack_depth
#else
#define FUNC_PROLOGUE

#define FUNC_EPILOGUE
#endif

#define UNREACHABLE TRAP(UNREACHABLE)

static inline bool func_types_eq(const wasm_rt_func_type_t a,
                                 const wasm_rt_func_type_t b) {
  return (a == b) || LIKELY(a && b && !memcmp(a, b, 32));
}

#define CHECK_CALL_INDIRECT(table, ft, x)                \
  (LIKELY((x) < table.size && table.data[x].func &&      \
          func_types_eq(ft, table.data[x].func_type)) || \
   TRAP(CALL_INDIRECT))

#define DO_CALL_INDIRECT(table, t, x, ...) ((t)table.data[x].func)(__VA_ARGS__)

#define CALL_INDIRECT(table, t, ft, x, ...) \
  (CHECK_CALL_INDIRECT(table, ft, x),       \
   DO_CALL_INDIRECT(table, t, x, __VA_ARGS__))

static inline bool add_overflow(uint64_t a, uint64_t b, uint64_t* resptr) {
#if __has_builtin(__builtin_add_overflow)
  return __builtin_add_overflow(a, b, resptr);
#elif defined(_MSC_VER)
  return _addcarry_u64(0, a, b, resptr);
#else
#error "Missing implementation of __builtin_add_overflow or _addcarry_u64"
#endif
}

#define RANGE_CHECK(mem, offset, len)              \
  do {                                             \
    uint64_t res;                                  \
    if (UNLIKELY(add_overflow(offset, len, &res))) \
      TRAP(OOB);                                   \
    if (UNLIKELY(res > (mem)->size))               \
      TRAP(OOB);                                   \
  } while (0);

#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && WASM_RT_SANITY_CHECKS
#include <stdio.h>
#define WASM_RT_CHECK_BASE(mem)                                               \
  if (((uintptr_t)((mem)->data)) != ((uintptr_t)wasm_rt_segue_read_base())) { \
    puts("Segment register mismatch\n");                                      \
    abort();                                                                  \
  }
#else
#define WASM_RT_CHECK_BASE(mem)
#endif

// MEMCHECK_DEFAULT32 is an "accelerated" MEMCHECK used only for
// default-page-size, 32-bit memories. It may do nothing at all
// (if hardware bounds-checking is enabled via guard pages)
// or it may do a slightly faster RANGE_CHECK.
#if WASM_RT_MEMCHECK_GUARD_PAGES
#define MEMCHECK_DEFAULT32(mem, a, t) WASM_RT_CHECK_BASE(mem);
#else
#define MEMCHECK_DEFAULT32(mem, a, t)                \
  WASM_RT_CHECK_BASE(mem);                           \
  if (UNLIKELY(a + (uint64_t)sizeof(t) > mem->size)) \
    TRAP(OOB);
#endif

// MEMCHECK_GENERAL can be used for any memory
#define MEMCHECK_GENERAL(mem, a, t) \
  WASM_RT_CHECK_BASE(mem);          \
  RANGE_CHECK(mem, a, sizeof(t));

#ifdef __GNUC__
#define FORCE_READ_INT(var) __asm__("" ::"r"(var));
// Clang on Mips requires "f" constraints on floats
// See https://github.com/llvm/llvm-project/issues/64241
#if defined(__clang__) && \
    (defined(mips) || defined(__mips__) || defined(__mips))
#define FORCE_READ_FLOAT(var) __asm__("" ::"f"(var));
#else
#define FORCE_READ_FLOAT(var) __asm__("" ::"r"(var));
#endif
#else
#define FORCE_READ_INT(var)
#define FORCE_READ_FLOAT(var)
#endif

static inline void load_data(u8* dest, const u8* src, size_t n) {
  if (!n) {
    return;
  }
#if WABT_BIG_ENDIAN
  for (size_t i = 0; i < n; i++) {
    dest[i] = src[n - i - 1];
  }
#else
  wasm_rt_memcpy(dest, src, n);
#endif
}

#define LOAD_DATA(m, o, i, s)            \
  do {                                   \
    RANGE_CHECK((&m), o, s);             \
    load_data(MEM_ADDR(&m, o, s), i, s); \
  } while (0)

#define DEF_MEM_CHECKS0(name, shared, mem_type, ret_kw, return_type)         \
  static inline return_type name##_default32(wasm_rt##shared##memory_t* mem, \
                                             u64 addr) {                     \
    MEMCHECK_DEFAULT32(mem, addr, mem_type);                                 \
    ret_kw name##_unchecked(mem, addr);                                      \
  }                                                                          \
  static inline return_type name(wasm_rt##shared##memory_t* mem, u64 addr) { \
    MEMCHECK_GENERAL(mem, addr, mem_type);                                   \
    ret_kw name##_unchecked(mem, addr);                                      \
  }

#define DEF_MEM_CHECKS1(name, shared, mem_type, ret_kw, return_type,         \
                        val_type1)                                           \
  static inline return_type name##_default32(wasm_rt##shared##memory_t* mem, \
                                             u64 addr, val_type1 val1) {     \
    MEMCHECK_DEFAULT32(mem, addr, mem_type);                                 \
    ret_kw name##_unchecked(mem, addr, val1);                                \
  }                                                                          \
  static inline return_type name(wasm_rt##shared##memory_t* mem, u64 addr,   \
                                 val_type1 val1) {                           \
    MEMCHECK_GENERAL(mem, addr, mem_type);                                   \
    ret_kw name##_unchecked(mem, addr, val1);                                \
  }

#define DEF_MEM_CHECKS2(name, shared, mem_type, ret_kw, return_type,         \
                        val_type1, val_type2)                                \
  static inline return_type name##_default32(wasm_rt##shared##memory_t* mem, \
                                             u64 addr, val_type1 val1,       \
                                             val_type2 val2) {               \
    MEMCHECK_DEFAULT32(mem, addr, mem_type);                                 \
    ret_kw name##_unchecked(mem, addr, val1, val2);                          \
  }                                                                          \
  static inline return_type name(wasm_rt##shared##memory_t* mem, u64 addr,   \
                                 val_type1 val1, val_type2 val2) {           \
    MEMCHECK_GENERAL(mem, addr, mem_type);                                   \
    ret_kw name##_unchecked(mem, addr, val1, val2);                          \
  }

#define DEFINE_LOAD(name, t1, t2, t3, force_read)                      \
  static inline t3 name##_unchecked(wasm_rt_memory_t* mem, u64 addr) { \
    t1 result;                                                         \
    wasm_rt_memcpy(&result, MEM_ADDR_MEMOP(mem, addr, sizeof(t1)),     \
                   sizeof(t1));                                        \
    force_read(result);                                                \
    return (t3)(t2)result;                                             \
  }                                                                    \
  DEF_MEM_CHECKS0(name, _, t1, return, t3)

#define DEFINE_STORE(name, t1, t2)                                     \
  static inline void name##_unchecked(wasm_rt_memory_t* mem, u64 addr, \
                                      t2 value) {                      \
    t1 wrapped = (t1)value;                                            \
    wasm_rt_memcpy(MEM_ADDR_MEMOP(mem, addr, sizeof(t1)), &wrapped,    \
                   sizeof(t1));                                        \
  }                                                                    \
  DEF_MEM_CHECKS1(name, _, t1, , void, t2)

DEFINE_LOAD(i32_load, u32, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load, u64, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(f32_load, f32, f32, f32, FORCE_READ_FLOAT)
DEFINE_LOAD(f64_load, f64, f64, f64, FORCE_READ_FLOAT)
DEFINE_LOAD(i32_load8_s, s8, s32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load8_s, s8, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load8_u, u8, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load8_u, u8, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load16_s, s16, s32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load16_s, s16, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i32_load16_u, u16, u32, u32, FORCE_READ_INT)
DEFINE_LOAD(i64_load16_u, u16, u64, u64, FORCE_READ_INT)
DEFINE_LOAD(i64_load32_s, s32, s64, u64, FORCE_READ_INT)
DEFINE_LOAD(i64_load32_u, u32, u64, u64, FORCE_READ_INT)
DEFINE_STORE(i32_store, u32, u32)
DEFINE_STORE(i64_store, u64, u64)
DEFINE_STORE(f32_store, f32, f32)
DEFINE_STORE(f64_store, f64, f64)
DEFINE_STORE(i32_store8, u8, u32)
DEFINE_STORE(i32_store16, u16, u32)
DEFINE_STORE(i64_store8, u8, u64)
DEFINE_STORE(i64_store16, u16, u64)
DEFINE_STORE(i64_store32, u32, u64)

#if defined(_MSC_VER)

// Adapted from
// https://github.com/nemequ/portable-snippets/blob/master/builtin/builtin.h

static inline int I64_CLZ(unsigned long long v) {
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  if (_BitScanReverse64(&r, v)) {
    return 63 - r;
  }
#else
  if (_BitScanReverse(&r, (unsigned long)(v >> 32))) {
    return 31 - r;
  } else if (_BitScanReverse(&r, (unsigned long)v)) {
    return 63 - r;
  }
#endif
  return 64;
}

static inline int I32_CLZ(unsigned long v) {
  unsigned long r = 0;
  if (_BitScanReverse(&r, v)) {
    return 31 - r;
  }
  return 32;
}

static inline int I64_CTZ(unsigned long long v) {
  if (!v) {
    return 64;
  }
  unsigned long r = 0;
#if defined(_M_AMD64) || defined(_M_ARM)
  _BitScanForward64(&r, v);
  return (int)r;
#else
  if (_BitScanForward(&r, (unsigned int)(v))) {
    return (int)(r);
  }

  _BitScanForward(&r, (unsigned int)(v >> 32));
  return (int)(r + 32);
#endif
}

static inline int I32_CTZ(unsigned long v) {
  if (!v) {
    return 32;
  }
  unsigned long r = 0;
  _BitScanForward(&r, v);
  return (int)r;
}

#define POPCOUNT_DEFINE_PORTABLE(f_n, T)                            \
  static inline u32 f_n(T x) {                                      \
    x = x - ((x >> 1) & (T) ~(T)0 / 3);                             \
    x = (x & (T) ~(T)0 / 15 * 3) + ((x >> 2) & (T) ~(T)0 / 15 * 3); \
    x = (x + (x >> 4)) & (T) ~(T)0 / 255 * 15;                      \
    return (T)(x * ((T) ~(T)0 / 255)) >> (sizeof(T) - 1) * 8;       \
  }

POPCOUNT_DEFINE_PORTABLE(I32_POPCNT, u32)
POPCOUNT_DEFINE_PORTABLE(I64_POPCNT, u64)

#undef POPCOUNT_DEFINE_PORTABLE

#else

#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)
#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)
#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)
#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)
#define I32_POPCNT(x) (__builtin_popcount(x))
#define I64_POPCNT(x) (__builtin_popcountll(x))

#endif

#define DIV_S(ut, min, x, y)                                  \
  ((UNLIKELY((y) == 0))                  ? TRAP(DIV_BY_ZERO)  \
   : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \
                                         : (ut)((x) / (y)))

#define REM_S(ut, min, x, y)                                 \
  ((UNLIKELY((y) == 0))                  ? TRAP(DIV_BY_ZERO) \
   : (UNLIKELY((x) == min && (y) == -1)) ? 0                 \
                                         : (ut)((x) % (y)))

#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)
#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)
#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)

#define DIVREM_U(op, x, y) \
  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x)op(y)))

#define DIV_U(x, y) DIVREM_U(/, x, y)
#define REM_U(x, y) DIVREM_U(%, x, y)

#define ROTL(x, y, mask) \
  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))
#define ROTR(x, y, mask) \
  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))

#define I32_ROTL(x, y) ROTL(x, y, 31)
#define I64_ROTL(x, y) ROTL(x, y, 63)
#define I32_ROTR(x, y) ROTR(x, y, 31)
#define I64_ROTR(x, y) ROTR(x, y, 63)

#define FMIN(x, y)                                           \
  ((UNLIKELY((x) != (x)))             ? NAN                  \
   : (UNLIKELY((y) != (y)))           ? NAN                  \
   : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \
   : (x < y)                          ? x                    \
                                      : y)

#define FMAX(x, y)                                           \
  ((UNLIKELY((x) != (x)))             ? NAN                  \
   : (UNLIKELY((y) != (y)))           ? NAN                  \
   : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \
   : (x > y)                          ? x                    \
                                      : y)

#define TRUNC_S(ut, st, ft, min, minop, max, x)                             \
  ((UNLIKELY((x) != (x)))                        ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x)minop(min) && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                 : (ut)(st)(x))

#define I32_TRUNC_S_F32(x) \
  TRUNC_S(u32, s32, f32, (f32)INT32_MIN, >=, 2147483648.f, x)
#define I64_TRUNC_S_F32(x) \
  TRUNC_S(u64, s64, f32, (f32)INT64_MIN, >=, (f32)INT64_MAX, x)
#define I32_TRUNC_S_F64(x) \
  TRUNC_S(u32, s32, f64, -2147483649., >, 2147483648., x)
#define I64_TRUNC_S_F64(x) \
  TRUNC_S(u64, s64, f64, (f64)INT64_MIN, >=, (f64)INT64_MAX, x)

#define TRUNC_U(ut, ft, max, x)                                              \
  ((UNLIKELY((x) != (x)))                         ? TRAP(INVALID_CONVERSION) \
   : (UNLIKELY(!((x) > (ft) - 1 && (x) < (max)))) ? TRAP(INT_OVERFLOW)       \
                                                  : (ut)(x))

#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, 4294967296.f, x)
#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, (f32)UINT64_MAX, x)
#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, 4294967296., x)
#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, (f64)UINT64_MAX, x)

#define TRUNC_SAT_S(ut, st, ft, min, smin, minop, max, smax, x) \
  ((UNLIKELY((x) != (x)))         ? 0                           \
   : (UNLIKELY(!((x)minop(min)))) ? smin                        \
   : (UNLIKELY(!((x) < (max))))   ? smax                        \
                                  : (ut)(st)(x))

#define I32_TRUNC_SAT_S_F32(x)                                            \
  TRUNC_SAT_S(u32, s32, f32, (f32)INT32_MIN, INT32_MIN, >=, 2147483648.f, \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F32(x)                                              \
  TRUNC_SAT_S(u64, s64, f32, (f32)INT64_MIN, INT64_MIN, >=, (f32)INT64_MAX, \
              INT64_MAX, x)
#define I32_TRUNC_SAT_S_F64(x)                                        \
  TRUNC_SAT_S(u32, s32, f64, -2147483649., INT32_MIN, >, 2147483648., \
              INT32_MAX, x)
#define I64_TRUNC_SAT_S_F64(x)                                              \
  TRUNC_SAT_S(u64, s64, f64, (f64)INT64_MIN, INT64_MIN, >=, (f64)INT64_MAX, \
              INT64_MAX, x)

#define TRUNC_SAT_U(ut, ft, max, smax, x) \
  ((UNLIKELY((x) != (x)))          ? 0    \
   : (UNLIKELY(!((x) > (ft) - 1))) ? 0    \
   : (UNLIKELY(!((x) < (max))))    ? smax \
                                   : (ut)(x))

#define I32_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u32, f32, 4294967296.f, UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F32(x) \
  TRUNC_SAT_U(u64, f32, (f32)UINT64_MAX, UINT64_MAX, x)
#define I32_TRUNC_SAT_U_F64(x) TRUNC_SAT_U(u32, f64, 4294967296., UINT32_MAX, x)
#define I64_TRUNC_SAT_U_F64(x) \
  TRUNC_SAT_U(u64, f64, (f64)UINT64_MAX, UINT64_MAX, x)

#define DEFINE_REINTERPRET(name, t1, t2)         \
  static inline t2 name(t1 x) {                  \
    t2 result;                                   \
    wasm_rt_memcpy(&result, &x, sizeof(result)); \
    return result;                               \
  }

DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)
DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)
DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)
DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)

static float quiet_nanf(float x) {
  uint32_t tmp;
  wasm_rt_memcpy(&tmp, &x, 4);
  tmp |= 0x7fc00000lu;
  wasm_rt_memcpy(&x, &tmp, 4);
  return x;
}

static double quiet_nan(double x) {
  uint64_t tmp;
  wasm_rt_memcpy(&tmp, &x, 8);
  tmp |= 0x7ff8000000000000llu;
  wasm_rt_memcpy(&x, &tmp, 8);
  return x;
}

static double wasm_quiet(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return x;
}

static float wasm_quietf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return x;
}

static double wasm_floor(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return floor(x);
}

static float wasm_floorf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return floorf(x);
}

static double wasm_ceil(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return ceil(x);
}

static float wasm_ceilf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return ceilf(x);
}

static double wasm_trunc(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return trunc(x);
}

static float wasm_truncf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return truncf(x);
}

static float wasm_nearbyintf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return nearbyintf(x);
}

static double wasm_nearbyint(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return nearbyint(x);
}

static float wasm_fabsf(float x) {
  if (UNLIKELY(isnan(x))) {
    uint32_t tmp;
    wasm_rt_memcpy(&tmp, &x, 4);
    tmp = tmp & ~(1UL << 31);
    wasm_rt_memcpy(&x, &tmp, 4);
    return x;
  }
  return fabsf(x);
}

static double wasm_fabs(double x) {
  if (UNLIKELY(isnan(x))) {
    uint64_t tmp;
    wasm_rt_memcpy(&tmp, &x, 8);
    tmp = tmp & ~(1ULL << 63);
    wasm_rt_memcpy(&x, &tmp, 8);
    return x;
  }
  return fabs(x);
}

static double wasm_sqrt(double x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nan(x);
  }
  return sqrt(x);
}

static float wasm_sqrtf(float x) {
  if (UNLIKELY(isnan(x))) {
    return quiet_nanf(x);
  }
  return sqrtf(x);
}

static inline void memory_fill(wasm_rt_memory_t* mem, u64 d, u32 val, u64 n) {
  RANGE_CHECK(mem, d, n);
  memset(MEM_ADDR(mem, d, n), val, n);
}

static inline void memory_copy(wasm_rt_memory_t* dest,
                               const wasm_rt_memory_t* src,
                               u64 dest_addr,
                               u64 src_addr,
                               u64 n) {
  RANGE_CHECK(dest, dest_addr, n);
  RANGE_CHECK(src, src_addr, n);
  memmove(MEM_ADDR(dest, dest_addr, n), MEM_ADDR(src, src_addr, n), n);
}

static inline void memory_init(wasm_rt_memory_t* dest,
                               const u8* src,
                               u32 src_size,
                               u64 dest_addr,
                               u32 src_addr,
                               u32 n) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  LOAD_DATA((*dest), dest_addr, src + src_addr, n);
}

typedef enum { RefFunc, RefNull, GlobalGet } wasm_elem_segment_expr_type_t;

typedef struct {
  wasm_elem_segment_expr_type_t expr_type;
  wasm_rt_func_type_t type;
  wasm_rt_function_ptr_t func;
  wasm_rt_tailcallee_t func_tailcallee;
  size_t module_offset;
} wasm_elem_segment_expr_t;

static inline void funcref_table_init(wasm_rt_funcref_table_t* dest,
                                      const wasm_elem_segment_expr_t* src,
                                      u32 src_size,
                                      u64 dest_addr,
                                      u32 src_addr,
                                      u32 n,
                                      void* module_instance) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  RANGE_CHECK(dest, dest_addr, n);
  for (u32 i = 0; i < n; i++) {
    const wasm_elem_segment_expr_t* const src_expr = &src[src_addr + i];
    wasm_rt_funcref_t* const dest_val = &(dest->data[dest_addr + i]);
    switch (src_expr->expr_type) {
      case RefFunc:
        *dest_val = (wasm_rt_funcref_t){
            src_expr->type, src_expr->func, src_expr->func_tailcallee,
            (char*)module_instance + src_expr->module_offset};
        break;
      case RefNull:
        *dest_val = wasm_rt_funcref_null_value;
        break;
      case GlobalGet:
        *dest_val = **(wasm_rt_funcref_t**)((char*)module_instance +
                                            src_expr->module_offset);
        break;
    }
  }
}

// Currently wasm2c only supports initializing externref tables with ref.null.
static inline void externref_table_init(wasm_rt_externref_table_t* dest,
                                        u32 src_size,
                                        u64 dest_addr,
                                        u32 src_addr,
                                        u32 n) {
  if (UNLIKELY(src_addr + (uint64_t)n > src_size))
    TRAP(OOB);
  RANGE_CHECK(dest, dest_addr, n);
  for (u32 i = 0; i < n; i++) {
    dest->data[dest_addr + i] = wasm_rt_externref_null_value;
  }
}

#define DEFINE_TABLE_COPY(type)                                              \
  static inline void type##_table_copy(wasm_rt_##type##_table_t* dest,       \
                                       const wasm_rt_##type##_table_t* src,  \
                                       u64 dest_addr, u64 src_addr, u64 n) { \
    RANGE_CHECK(dest, dest_addr, n);                                         \
    RANGE_CHECK(src, src_addr, n);                                           \
    memmove(dest->data + dest_addr, src->data + src_addr,                    \
            n * sizeof(wasm_rt_##type##_t));                                 \
  }

DEFINE_TABLE_COPY(funcref)
DEFINE_TABLE_COPY(externref)

#define DEFINE_TABLE_GET(type)                        \
  static inline wasm_rt_##type##_t type##_table_get(  \
      const wasm_rt_##type##_table_t* table, u64 i) { \
    if (UNLIKELY(i >= table->size))                   \
      TRAP(OOB);                                      \
    return table->data[i];                            \
  }

DEFINE_TABLE_GET(funcref)
DEFINE_TABLE_GET(externref)

#define DEFINE_TABLE_SET(type)                                               \
  static inline void type##_table_set(const wasm_rt_##type##_table_t* table, \
                                      u64 i, const wasm_rt_##type##_t val) { \
    if (UNLIKELY(i >= table->size))                                          \
      TRAP(OOB);                                                             \
    table->data[i] = val;                                                    \
  }

DEFINE_TABLE_SET(funcref)
DEFINE_TABLE_SET(externref)

#define DEFINE_TABLE_FILL(type)                                               \
  static inline void type##_table_fill(const wasm_rt_##type##_table_t* table, \
                                       u64 d, const wasm_rt_##type##_t val,   \
                                       u64 n) {                               \
    RANGE_CHECK(table, d, n);                                                 \
    for (uint32_t i = d; i < d + n; i++) {                                    \
      table->data[i] = val;                                                   \
    }                                                                         \
  }

DEFINE_TABLE_FILL(funcref)
DEFINE_TABLE_FILL(externref)

#if defined(__GNUC__) || defined(__clang__)
#define FUNC_TYPE_DECL_EXTERN_T(x) extern const char* const x
#define FUNC_TYPE_EXTERN_T(x) const char* const x
#define FUNC_TYPE_T(x) static const char* const x
#else
#define FUNC_TYPE_DECL_EXTERN_T(x) extern const char x[]
#define FUNC_TYPE_EXTERN_T(x) const char x[]
#define FUNC_TYPE_T(x) static const char x[]
#endif

#if (__STDC_VERSION__ < 201112L) && !defined(static_assert)
#define static_assert(X) \
  extern int(*assertion(void))[!!sizeof(struct { int x : (X) ? 2 : -1; })];
#endif

#ifdef _MSC_VER
#define WEAK_FUNC_DECL(func, fallback)                             \
  __pragma(comment(linker, "/alternatename:" #func "=" #fallback)) \
                                                                   \
      void                                                         \
      fallback(void** instance_ptr, void* tail_call_stack,         \
               wasm_rt_tailcallee_t* next)
#else
#define WEAK_FUNC_DECL(func, fallback)                                        \
  __attribute__((weak)) void func(void** instance_ptr, void* tail_call_stack, \
                                  wasm_rt_tailcallee_t* next)
#endif

static u32 w2c_prog_f6(w2c_prog*, u64);
static void w2c_prog_f7(w2c_prog*, u32);
static u32 w2c_prog_f8(w2c_prog*, u32, u32);
static u32 w2c_prog_f9(w2c_prog*, u32, u32);
static u32 w2c_prog_f10(w2c_prog*, u32);
static u32 w2c_prog_f11(w2c_prog*, u32, u32);
static u32 w2c_prog_f12(w2c_prog*, u32, u32, u32);
static u32 w2c_prog_f13(w2c_prog*, u32, u32, u64);
static void w2c_prog_f14(w2c_prog*, u32, u32, u32, u32, u32);
static void w2c_prog_f15(w2c_prog*, u32);
static void w2c_prog_f16(w2c_prog*, u32, u64, u32);
static u64 w2c_prog_f17(w2c_prog*);
static u32 w2c_prog_f18(w2c_prog*, u64, u32);
static u32 w2c_prog_f19(w2c_prog*, u32, u32, u32);
static u32 w2c_prog_f20(w2c_prog*, u32, u32, u32);
static u32 w2c_prog_f21(w2c_prog*, u32, u32);
static u32 w2c_prog_f22(w2c_prog*, u32, u32);
static void w2c_prog_f23(w2c_prog*, u32, u32, u32, u32);
static u32 w2c_prog_f24(w2c_prog*, u32, u32, u64, u32);
static void w2c_prog_0x5Fstart_0(w2c_prog*);

FUNC_TYPE_T(w2c_prog_t0) = "\xf6\x98\x1b\xc6\x10\xda\xb7\xb2\x63\x37\xcd\xdc\x72\xca\xe9\x50\x00\x13\xba\x10\x6c\xde\x87\x27\x10\xf8\x86\x2f\xe3\xdb\x94\xe4";
FUNC_TYPE_T(w2c_prog_t1) = "\x07\x80\x96\x7a\x42\xf7\x3e\xe6\x70\x5c\x2f\xac\x83\xf5\x67\xd2\xa2\xa0\x69\x41\x5f\xf8\xe7\x96\x7f\x23\xab\x00\x03\x5f\x4a\x3c";
FUNC_TYPE_T(w2c_prog_t2) = "\x89\x3a\x3d\x2c\x8f\x4d\x7f\x6d\x6c\x9d\x62\x67\x29\xaf\x3d\x44\x39\x8e\xc3\xf3\xe8\x51\xc1\x99\xb9\xdd\x9f\xd5\x3d\x1f\xd3\xe4";
FUNC_TYPE_T(w2c_prog_t3) = "\xc8\xb4\x32\x7f\x30\xd6\x74\x1d\x89\x51\xbd\x55\x66\xa6\xfc\x17\x99\x53\xb1\x2b\xb7\x54\xd3\xed\xd0\x03\x38\xd2\x22\x94\xfa\x72";
FUNC_TYPE_T(w2c_prog_t4) = "\x92\xfb\x6a\xdf\x49\x07\x0a\x83\xbe\x08\x02\x68\xcd\xf6\x95\x27\x4a\xc2\xf3\xe5\xe4\x7d\x29\x49\xe8\xed\x42\x92\x6a\x9d\xda\xf0";
FUNC_TYPE_T(w2c_prog_t5) = "\x6c\x9c\x53\x1a\xdd\x7f\xe5\x69\x16\x4e\x66\x8f\xa2\x8f\x87\xd9\xf8\x67\x49\x93\xe3\x5b\x65\x89\xc6\xca\xf0\x41\x42\xb5\x6e\x82";
FUNC_TYPE_T(w2c_prog_t6) = "\x36\xb2\x3b\x59\x0e\xe1\x68\x15\x39\xbd\x13\x39\xf5\xe5\xc8\x9b\x43\xd8\xb0\x6d\x5d\x5d\x18\xc2\x38\x45\x2d\x0e\x6b\x81\x8f\x8f";
FUNC_TYPE_T(w2c_prog_t7) = "\xcd\xad\x8f\x6a\xaf\x3e\xd0\x86\xf0\x9a\xd7\xf0\xc7\x0d\x48\x9f\x27\x59\xf3\x8d\x71\xa1\x81\xa8\xcc\x06\x53\x98\x62\x34\xaa\xf5";
FUNC_TYPE_T(w2c_prog_t8) = "\x91\x86\x55\xe8\x24\x75\x9f\xb0\x6c\xda\x59\xe0\x29\x61\xcf\xfa\x48\xe7\x19\x9e\x61\xbe\x87\xaf\xe2\xc8\x91\x77\x73\xc7\x82\x38";
FUNC_TYPE_T(w2c_prog_t9) = "\x10\x14\x42\x90\xbf\xa8\x37\x8c\xdc\x81\x9f\x4c\x63\x4e\x62\xb7\x11\x29\xaa\x09\x68\x89\x5f\x5e\x13\x9c\xcc\xe2\xcb\x51\x7a\x78";
FUNC_TYPE_T(w2c_prog_t10) = "\x17\x77\x40\x5c\x24\xdb\x90\x77\x5b\x46\x48\x9a\x9b\xd9\xbe\x31\x10\x45\x47\x07\xdc\x34\x95\xdc\xd0\xc4\x51\xe1\x14\xe8\x08\x47";
FUNC_TYPE_T(w2c_prog_t11) = "\xa6\x83\x1a\x14\xc3\x06\xed\xb0\xc1\xda\x87\x2f\x07\x53\x23\x00\xfd\x3d\xd0\x1d\x58\xab\xd8\xbf\xcf\x54\xdb\xc5\x02\xc8\x07\x27";
FUNC_TYPE_T(w2c_prog_t12) = "\xc1\x35\x64\x94\x2d\x55\x73\x56\xf4\xe1\x63\x0d\x0e\xe1\x22\x79\x32\x48\xe9\x1a\x10\x0b\x2b\x94\x08\xe2\xbe\x33\x0f\x6d\x15\x99";
FUNC_TYPE_T(w2c_prog_t13) = "\xff\x57\x1f\x83\x74\x67\x5d\x67\x2a\xc8\x0d\x92\x3d\xe8\x47\xa1\x1e\x73\xc7\x03\xa1\xee\x83\x72\x66\xa9\x1c\x9d\xe7\x8c\xdd\xfb";
FUNC_TYPE_T(w2c_prog_t14) = "\xc0\x60\x20\xa5\xf9\x46\xaf\x7e\xca\xe6\x19\x5d\x24\xfb\x1c\x27\x67\x4e\x29\x89\x8e\x69\x68\x17\xa9\x3a\x39\xf9\x56\x59\xbb\x1d";
FUNC_TYPE_T(w2c_prog_t15) = "\x36\xa9\xe7\xf1\xc9\x5b\x82\xff\xb9\x97\x43\xe0\xc5\xc4\xce\x95\xd8\x3c\x9a\x43\x0a\xac\x59\xf8\x4e\xf3\xcb\xfa\xb6\x14\x50\x68";

static void init_globals(w2c_prog* instance) {
  instance->w2c_g0 = 8257536u;
  instance->w2c_g1 = 8258816u;
}

static const u8 data_segment_data_w2c_prog_d0[] = {
  0x01, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x60, 
};

static const u8 data_segment_data_w2c_prog_d1[] = {
  0x0d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x63, 0x61, 0x6e, 0x6e, 
  0x6f, 0x74, 0x20, 0x6c, 0x69, 0x73, 0x74, 0x20, 0x60, 
};

static const u8 data_segment_data_w2c_prog_d2[] = {
  0x13, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x61, 0x72, 0x72, 0x61, 0x79, 0x20, 0x69, 0x6e, 0x64, 
  0x65, 0x78, 0x20, 0x00, 0x0f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 
  0x20, 0x6f, 0x75, 0x74, 0x20, 0x6f, 0x66, 0x20, 0x62, 0x6f, 0x75, 0x6e, 
  0x64, 0x73, 0x0a, 0x00, 0x14, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 
  0x65, 0x72, 0x72, 0x6f, 0x72, 0x3a, 0x20, 0x73, 0x74, 0x72, 0x69, 0x6e, 
  0x67, 0x20, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x20, 0x00, 0x00, 0x00, 0x00, 
  0x18, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x20, 
  0x62, 0x79, 0x20, 0x7a, 0x65, 0x72, 0x6f, 0x0a, 0x00, 0x00, 0x00, 0x00, 
  0x19, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x64, 0x65, 0x72, 
  0x20, 0x62, 0x79, 0x20, 0x7a, 0x65, 0x72, 0x6f, 0x0a, 0x00, 0x00, 0x00, 
  0x24, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x20, 0x6f, 
  0x76, 0x65, 0x72, 0x66, 0x6c, 0x6f, 0x77, 0x20, 0x69, 0x6e, 0x20, 0x64, 
  0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x0a, 0x00, 0x00, 0x00, 0x00, 
  0x21, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x73, 0x68, 0x69, 0x66, 0x74, 0x20, 0x61, 0x6d, 0x6f, 
  0x75, 0x6e, 0x74, 0x20, 0x6f, 0x75, 0x74, 0x20, 0x6f, 0x66, 0x20, 0x72, 
  0x61, 0x6e, 0x67, 0x65, 0x0a, 0x00, 0x00, 0x00, 0x1f, 0x00, 0x00, 0x00, 
  0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x3a, 0x20, 0x63, 
  0x61, 0x6c, 0x6c, 0x20, 0x64, 0x65, 0x70, 0x74, 0x68, 0x20, 0x65, 0x78, 
  0x63, 0x65, 0x65, 0x64, 0x73, 0x20, 0x31, 0x30, 0x30, 0x30, 0x0a, 0x00, 
  0x21, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x20, 0x6e, 0x65, 
  0x73, 0x74, 0x69, 0x6e, 0x67, 0x20, 0x65, 0x78, 0x63, 0x65, 0x65, 0x64, 
  0x73, 0x20, 0x36, 0x34, 0x0a, 0x00, 0x00, 0x00, 0x28, 0x01, 0x7e, 0x00, 
  0x44, 0x01, 0x7e, 0x00, 0x5c, 0x01, 0x7e, 0x00, 0x44, 0x01, 0x7e, 0x00, 
  0x7c, 0x01, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x00, 0xa0, 0x01, 0x7e, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0xc4, 0x01, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x00, 
  0xf4, 0x01, 0x7e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x20, 0x02, 0x7e, 0x00, 
  0x00, 0x00, 0x00, 0x00, 0x48, 0x02, 0x7e, 
};

static const u8 data_segment_data_w2c_prog_d3[] = {
  0x01, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x2e, 
};

static const u8 data_segment_data_w2c_prog_d4[] = {
  0x07, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x65, 0x72, 0x72, 0x6f, 
  0x72, 0x3a, 0x20, 0x00, 0x01, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 
  0x0a, 
};

static const u8 data_segment_data_w2c_prog_d5[] = {
  0x0d, 0x00, 0x00, 0x00, 0xff, 0xff, 0xff, 0xff, 0x6f, 0x75, 0x74, 0x20, 
  0x6f, 0x66, 0x20, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 
};

static void init_memories(w2c_prog* instance) {
  wasm_rt_allocate_memory(&instance->w2c_memory, 127, 65536, 0, 65536);
  LOAD_DATA(instance->w2c_memory, 8257616u, data_segment_data_w2c_prog_d0, 9);
  LOAD_DATA(instance->w2c_memory, 8257768u, data_segment_data_w2c_prog_d1, 21);
  LOAD_DATA(instance->w2c_memory, 8257824u, data_segment_data_w2c_prog_d2, 391);
  LOAD_DATA(instance->w2c_memory, 8258664u, data_segment_data_w2c_prog_d3, 9);
  LOAD_DATA(instance->w2c_memory, 8258700u, data_segment_data_w2c_prog_d4, 25);
  LOAD_DATA(instance->w2c_memory, 8258792u, data_segment_data_w2c_prog_d5, 21);
}

static void init_data_instances(w2c_prog *instance) {
}

/* export: '_start' */
void w2c_prog_0x5Fstart(w2c_prog* instance) {
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
  w2c_prog_0x5Fstart_0(instance);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
}

/* export: 'memory' */
wasm_rt_memory_t* w2c_prog_memory(w2c_prog* instance) {
  return &instance->w2c_memory;
}

static void init_instance_import(w2c_prog* instance, struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance) {
  instance->w2c_wasi__snapshot__preview1_instance = w2c_wasi__snapshot__preview1_instance;
}

void wasm2c_prog_instantiate(w2c_prog* instance, struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance) {
  assert(wasm_rt_is_initialized());
  init_instance_import(instance, w2c_wasi__snapshot__preview1_instance);
  init_globals(instance);
  init_memories(instance);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
#if !WASM_RT_SEGUE_FREE_SEGMENT
  void* segue_saved_base = wasm_rt_segue_read_base();
#endif
  wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
  init_data_instances(instance);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE && !WASM_RT_SEGUE_FREE_SEGMENT
  wasm_rt_segue_write_base(segue_saved_base);
#endif
}

void wasm2c_prog_free(w2c_prog* instance) {
  wasm_rt_free_memory(&instance->w2c_memory);
}

wasm_rt_func_type_t wasm2c_prog_get_func_type(uint32_t param_count, uint32_t result_count, ...) {
  va_list args;
  
  if (param_count == 4 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t0;
    }
    va_end(args);
  }
  
  if (param_count == 1 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t1;
    }
    va_end(args);
  }
  
  if (param_count == 1 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t2;
    }
    va_end(args);
  }
  
  if (param_count == 9 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t3;
    }
    va_end(args);
  }
  
  if (param_count == 2 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t4;
    }
    va_end(args);
  }
  
  if (param_count == 5 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t5;
    }
    va_end(args);
  }
  
  if (param_count == 1 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t6;
    }
    va_end(args);
  }
  
  if (param_count == 3 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t7;
    }
    va_end(args);
  }
  
  if (param_count == 3 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t8;
    }
    va_end(args);
  }
  
  if (param_count == 5 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t9;
    }
    va_end(args);
  }
  
  if (param_count == 3 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t10;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I64) {
      va_end(args);
      return w2c_prog_t11;
    }
    va_end(args);
  }
  
  if (param_count == 2 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t12;
    }
    va_end(args);
  }
  
  if (param_count == 4 && result_count == 0) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t13;
    }
    va_end(args);
  }
  
  if (param_count == 4 && result_count == 1) {
    va_start(args, result_count);
    if (true && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I64 && va_arg(args, int) == WASM_RT_I32 && va_arg(args, int) == WASM_RT_I32) {
      va_end(args);
      return w2c_prog_t14;
    }
    va_end(args);
  }
  
  if (param_count == 0 && result_count == 0) {
    va_start(args, result_count);
    if (true) {
      va_end(args);
      return w2c_prog_t15;
    }
    va_end(args);
  }
  
  return NULL;
}

u32 w2c_prog_f6(w2c_prog* instance, u64 var_p0) {
  u32 var_l1 = 0, var_l2 = 0, var_l4 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, 
      var_l10 = 0, var_l11 = 0, var_l12 = 0, var_l13 = 0, var_l14 = 0, var_l15 = 0, var_l16 = 0, var_l20 = 0;
  u64 var_l3 = 0, var_l17 = 0, var_l18 = 0, var_l19 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j0, var_j1, var_j2;
  var_j0 = var_p0;
  var_j1 = 2147483648ull;
  var_i0 = var_j0 > var_j1;
  if (var_i0) {
    var_i0 = 8258800u;
    var_l4 = var_i0;
    var_i0 = 2u;
    var_i1 = 8258708u;
    var_i2 = 7u;
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 2u;
    var_i1 = var_l4;
    var_i2 = var_l4;
    var_i3 = 8u;
    var_i2 -= var_i3;
    var_i2 = i32_load_default32(&instance->w2c_memory, (u64)(var_i2));
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 8258724u;
    w2c_prog_f15(instance, var_i0);
    UNREACHABLE;
  }
  var_j0 = var_p0;
  var_j1 = 7ull;
  var_j0 += var_j1;
  var_j1 = 8ull;
  var_j2 = 18446744073709551615ull;
  var_j1 *= var_j2;
  var_j0 &= var_j1;
  var_i0 = (u32)(var_j0);
  var_l5 = var_i0;
  var_i0 = var_l5;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_j0 = 8ull;
    var_i0 = (u32)(var_j0);
    var_l5 = var_i0;
  }
  var_i0 = var_l5;
  var_j1 = 1ull;
  var_i1 = (u32)(var_j1);
  var_i0 -= var_i1;
  var_l5 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l6 = var_i0;
  var_i0 = var_l5;
  var_j1 = 2ull;
  var_i1 = (u32)(var_j1);
  var_l7 = var_i1;
  var_l8 = var_i0;
  var_i0 = var_l7;
  var_i1 = 32u;
  var_i0 = var_i0 >= var_i1;
  if (var_i0) {
    var_i0 = 5u;
    var_l2 = var_i0;
    var_j0 = 0ull;
    var_l3 = var_j0;
    goto var_B1;
  }
  var_i0 = var_l8;
  var_i1 = var_l7;
  var_i0 = (u32)((s32)var_i0 >> (var_i1 & 31));
  var_l9 = var_i0;
  var_L6: 
    var_i0 = var_l9;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B5;}
    var_i0 = var_l9;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_l7 = var_i1;
    var_l8 = var_i0;
    var_i0 = var_l7;
    var_i1 = 32u;
    var_i0 = var_i0 >= var_i1;
    if (var_i0) {
      var_i0 = 5u;
      var_l2 = var_i0;
      var_j0 = 0ull;
      var_l3 = var_j0;
      goto var_B1;
    }
    var_i0 = var_l8;
    var_i1 = var_l7;
    var_i0 = (u32)((s32)var_i0 >> (var_i1 & 31));
    var_l9 = var_i0;
    var_i0 = var_l6;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l6 = var_i0;
    goto var_L6;
  var_B5:;
  var_i0 = var_l5;
  var_i1 = var_l6;
  var_l7 = var_i1;
  var_l8 = var_i0;
  var_i0 = var_l7;
  var_i1 = 32u;
  var_i0 = var_i0 >= var_i1;
  if (var_i0) {
    var_i0 = 5u;
    var_l2 = var_i0;
    var_j0 = 0ull;
    var_l3 = var_j0;
    goto var_B1;
  }
  var_i0 = var_l8;
  var_i1 = var_l7;
  var_i0 = (u32)((s32)var_i0 >> (var_i1 & 31));
  var_j1 = 3ull;
  var_i1 = (u32)(var_j1);
  var_i0 &= var_i1;
  var_l10 = var_i0;
  var_i0 = var_l6;
  var_j1 = 2ull;
  var_i1 = (u32)(var_j1);
  var_l7 = var_i1;
  var_l8 = var_i0;
  var_i0 = var_l7;
  var_i1 = 32u;
  var_i0 = var_i0 >= var_i1;
  if (var_i0) {
    var_i0 = 5u;
    var_l2 = var_i0;
    var_j0 = 0ull;
    var_l3 = var_j0;
    goto var_B1;
  }
  var_i0 = var_l8;
  var_i1 = var_l7;
  var_i0 <<= (var_i1 & 31);
  var_i1 = var_l10;
  var_i0 += var_i1;
  var_l11 = var_i0;
  var_i0 = var_l10;
  var_j1 = 5ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_l6;
  var_l7 = var_i1;
  var_l8 = var_i0;
  var_i0 = var_l7;
  var_i1 = 32u;
  var_i0 = var_i0 >= var_i1;
  if (var_i0) {
    var_i0 = 5u;
    var_l2 = var_i0;
    var_j0 = 0ull;
    var_l3 = var_j0;
    goto var_B1;
  }
  var_i0 = var_l8;
  var_i1 = var_l7;
  var_i0 <<= (var_i1 & 31);
  var_l12 = var_i0;
  var_i0 = instance->w2c_g1;
  var_l13 = var_i0;
  var_i0 = var_l13;
  var_i1 = var_l11;
  var_j2 = 2ull;
  var_i2 = (u32)(var_j2);
  var_l7 = var_i2;
  var_l8 = var_i1;
  var_i1 = var_l7;
  var_i2 = 32u;
  var_i1 = var_i1 >= var_i2;
  if (var_i1) {
    var_i1 = 5u;
    var_l2 = var_i1;
    var_j1 = 0ull;
    var_l3 = var_j1;
    goto var_B1;
  }
  var_i1 = var_l8;
  var_i2 = var_l7;
  var_i1 <<= (var_i2 & 31);
  var_i0 += var_i1;
  var_l14 = var_i0;
  var_i0 = var_l14;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l15 = var_i0;
  var_i0 = var_l15;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    var_i0 = var_l14;
    var_i1 = var_l15;
    var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l15;
    goto var_B0;
  }
  var_i0 = var_l13;
  var_j1 = 8768ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_l13;
  var_j2 = 464ull;
  var_i2 = (u32)(var_j2);
  var_i1 += var_i2;
  var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
  var_i0 += var_i1;
  var_l16 = var_i0;
  var_i0 = var_l16;
  var_j0 = (u64)(var_i0);
  var_i1 = var_l12;
  var_j1 = (u64)(s64)(s32)(var_i1);
  var_j0 += var_j1;
  var_j1 = 8ull;
  var_j0 += var_j1;
  var_l17 = var_j0;
  var_j0 = var_l17;
  var_j1 = 4294967295ull;
  var_i0 = (u64)((s64)var_j0 > (s64)var_j1);
  if (var_i0) {
    var_i0 = 8258800u;
    var_l4 = var_i0;
    var_i0 = 2u;
    var_i1 = 8258708u;
    var_i2 = 7u;
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 2u;
    var_i1 = var_l4;
    var_i2 = var_l4;
    var_i3 = 8u;
    var_i2 -= var_i3;
    var_i2 = i32_load_default32(&instance->w2c_memory, (u64)(var_i2));
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 8258724u;
    w2c_prog_f15(instance, var_i0);
    UNREACHABLE;
  }
  var_j0 = var_l17;
  var_j1 = 65535ull;
  var_j0 += var_j1;
  var_j1 = 16ull;
  var_l18 = var_j1;
  var_l19 = var_j0;
  var_j0 = var_l18;
  var_j1 = 64ull;
  var_i0 = var_j0 >= var_j1;
  if (var_i0) {
    var_i0 = 5u;
    var_l2 = var_i0;
    var_j0 = 0ull;
    var_l3 = var_j0;
    goto var_B1;
  }
  var_j0 = var_l19;
  var_j1 = var_l18;
  var_j0 = (u64)((s64)var_j0 >> (var_j1 & 63));
  var_i0 = (u32)(var_j0);
  var_i1 = instance->w2c_memory.pages;
  var_i0 -= var_i1;
  var_l20 = var_i0;
  var_i0 = var_l20;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
  if (var_i0) {
    var_i0 = var_l20;
    var_i0 = wasm_rt_grow_memory(&instance->w2c_memory, var_i0);
#if WASM_RT_USE_SEGUE_FOR_THIS_MODULE
    wasm_rt_segue_write_base(instance->w2c_memory.data);
#endif
    var_j1 = 1ull;
    var_j2 = 18446744073709551615ull;
    var_j1 *= var_j2;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_i0 = 8258800u;
      var_l4 = var_i0;
      var_i0 = 2u;
      var_i1 = 8258708u;
      var_i2 = 7u;
      var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
      var_i0 = 2u;
      var_i1 = var_l4;
      var_i2 = var_l4;
      var_i3 = 8u;
      var_i2 -= var_i3;
      var_i2 = i32_load_default32(&instance->w2c_memory, (u64)(var_i2));
      var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
      var_i0 = 8258724u;
      w2c_prog_f15(instance, var_i0);
      UNREACHABLE;
    }
  }
  var_i0 = var_l13;
  var_j1 = 464ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_j1 = var_l17;
  var_i2 = var_l13;
  var_j2 = (u64)(s64)(s32)(var_i2);
  var_j1 -= var_j2;
  var_j2 = 8768ull;
  var_j1 -= var_j2;
  var_i1 = (u32)(var_j1);
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l16;
  var_i1 = var_l11;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l16;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  goto var_B0;
  var_B1:;
  var_i0 = var_l2;
  var_j1 = var_l3;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_prog_f7(w2c_prog* instance, u32 var_p0) {
  u32 var_l1 = 0, var_l2 = 0, var_l4 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0;
  u64 var_l3 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j1, var_j2;
  var_i0 = instance->w2c_g1;
  var_l4 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_l4;
  var_i0 = var_i0 < var_i1;
  if (var_i0) {
    goto var_B0;
  }
  var_i0 = var_p0;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 -= var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l5 = var_i0;
  var_i0 = var_l5;
  var_j1 = 3ull;
  var_i1 = (u32)(var_j1);
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_i0 = 1u;
  } else {
    var_i0 = var_l5;
    var_j1 = 115ull;
    var_i1 = (u32)(var_j1);
    var_i0 = (u32)((s32)var_i0 > (s32)var_i1);
  }
  if (var_i0) {
    goto var_B0;
  }
  var_i0 = var_l4;
  var_i1 = var_l5;
  var_j2 = 2ull;
  var_i2 = (u32)(var_j2);
  var_l6 = var_i2;
  var_l7 = var_i1;
  var_i1 = var_l6;
  var_i2 = 32u;
  var_i1 = var_i1 >= var_i2;
  if (var_i1) {
    var_i1 = 5u;
    var_l2 = var_i1;
    var_j1 = 0ull;
    var_l3 = var_j1;
    goto var_B1;
  }
  var_i1 = var_l7;
  var_i2 = var_l6;
  var_i1 <<= (var_i2 & 31);
  var_i0 += var_i1;
  var_l8 = var_i0;
  var_i0 = var_p0;
  var_i1 = var_l8;
  var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l8;
  var_i1 = var_p0;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  goto var_B0;
  var_B1:;
  var_i0 = var_l2;
  var_j1 = var_l3;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
}

u32 w2c_prog_f8(w2c_prog* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0;
  u64 var_l4 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j0, var_j1;
  var_i0 = instance->w2c_g1;
  var_l5 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l6 = var_i0;
  var_i0 = var_l5;
  var_j1 = 476ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    var_i0 = var_p1;
    var_j0 = (u64)(s64)(s32)(var_i0);
    var_j1 = 9ull;
    var_j0 += var_j1;
    var_i1 = var_l5;
    var_i0 = w2c_prog_f18(instance, var_j0, var_i1);
    var_l6 = var_i0;
  } else {
    var_i0 = var_p1;
    var_j0 = (u64)(s64)(s32)(var_i0);
    var_j1 = 9ull;
    var_j0 += var_j1;
    var_i0 = w2c_prog_f6(instance, var_j0);
    var_l6 = var_i0;
  }
  var_i0 = var_l6;
  var_i1 = var_p0;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l6;
  var_j1 = 4ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_p1;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l6;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_l7 = var_i0;
  var_i0 = var_l7;
  var_i1 = var_p0;
  var_i0 += var_i1;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i2 = 255u;
  var_i1 &= var_i2;
  i32_store8_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l7;
  goto var_B0;
  var_i0 = var_l3;
  var_j1 = var_l4;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f9(w2c_prog* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0;
  u64 var_l4 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j1, var_j3;
  var_i0 = var_p0;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 -= var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l5 = var_i0;
  var_i0 = var_p1;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 -= var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l6 = var_i0;
  var_i0 = var_l5;
  var_i1 = var_l6;
  var_i0 += var_i1;
  var_i1 = var_l5;
  var_i2 = var_l6;
  var_i1 += var_i2;
  var_i0 = w2c_prog_f8(instance, var_i0, var_i1);
  var_l7 = var_i0;
  var_i0 = var_l7;
  var_i1 = var_p0;
  var_i2 = var_l5;
  memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
  var_i0 = var_l7;
  var_i1 = var_l5;
  var_i0 += var_i1;
  var_i1 = var_p1;
  var_i2 = var_l6;
  var_j3 = 1ull;
  var_i3 = (u32)(var_j3);
  var_i2 += var_i3;
  memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
  var_i0 = var_l7;
  goto var_B0;
  var_i0 = var_l3;
  var_j1 = var_l4;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f10(w2c_prog* instance, u32 var_p0) {
  u32 var_l1 = 0, var_l2 = 0, var_l4 = 0;
  u64 var_l3 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j1;
  var_i0 = var_p0;
  var_l4 = var_i0;
  var_L3: 
    var_i0 = var_l4;
    var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i2 = 255u;
    var_i1 &= var_i2;
    var_i0 = var_i0 != var_i1;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B2;}
    var_i0 = var_l4;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l4 = var_i0;
    goto var_L3;
  var_B2:;
  var_i0 = var_l4;
  var_i1 = var_p0;
  var_i0 -= var_i1;
  goto var_B0;
  var_i0 = var_l2;
  var_j1 = var_l3;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f11(w2c_prog* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0;
  u64 var_l4 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j0, var_j1;
  var_i0 = var_p0;
  var_l5 = var_i0;
  var_i0 = var_p1;
  var_l6 = var_i0;
  var_L3: 
    var_i0 = 1u;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B2;}
    var_i0 = var_l5;
    var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l7 = var_i0;
    var_i0 = var_l6;
    var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l8 = var_i0;
    var_i0 = var_l7;
    var_i1 = var_l8;
    var_i0 = var_i0 != var_i1;
    if (var_i0) {
      var_i0 = var_l7;
      var_i1 = var_l8;
      var_i0 -= var_i1;
      goto var_B0;
    }
    var_i0 = var_l7;
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i2 = 255u;
    var_i1 &= var_i2;
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_j0 = 0ull;
      var_i0 = (u32)(var_j0);
      goto var_B0;
    }
    var_i0 = var_l5;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l5 = var_i0;
    var_i0 = var_l6;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l6 = var_i0;
    goto var_L3;
  var_B2:;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  goto var_B0;
  var_i0 = var_l3;
  var_j1 = var_l4;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f12(w2c_prog* instance, u32 var_p0, u32 var_p1, u32 var_p2) {
  u32 var_l3 = 0, var_l4 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, var_l11 = 0;
  u64 var_l5 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j0, var_j1, var_j2;
  var_i0 = instance->w2c_g1;
  var_l6 = var_i0;
  var_i0 = var_p0;
  var_j1 = 1ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = var_p2;
    var_j1 = 4096ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 < var_i1;
  } else {
    var_i0 = 0u;
  }
  var_l7 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l8 = var_i0;
  var_i0 = var_l6;
  var_j1 = 4576ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l9 = var_i0;
  var_i0 = var_l9;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    var_i0 = var_l7;
    var_i0 = !(var_i0);
    if (var_i0) {
      var_i0 = 1u;
    } else {
      var_i0 = var_l9;
      var_i1 = var_p2;
      var_i0 += var_i1;
      var_j1 = 4096ull;
      var_i1 = (u32)(var_j1);
      var_i0 = var_i0 > var_i1;
    }
  } else {
    var_i0 = 0u;
  }
  if (var_i0) {
    var_i0 = var_l6;
    var_j1 = 4576ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_j0 = 1ull;
    var_i0 = (u32)(var_j0);
    var_i1 = var_l6;
    var_j2 = 480ull;
    var_i2 = (u32)(var_j2);
    var_i1 += var_i2;
    var_i2 = var_l9;
    var_i0 = w2c_prog_f19(instance, var_i0, var_i1, var_i2);
    var_l8 = var_i0;
  }
  var_i0 = var_l7;
  if (var_i0) {
    var_i0 = var_l6;
    var_j1 = 4576ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l10 = var_i0;
    var_i0 = var_l6;
    var_j1 = 480ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i1 = var_l10;
    var_i0 += var_i1;
    var_i1 = var_p1;
    var_i2 = var_p2;
    memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
    var_i0 = var_l6;
    var_j1 = 4576ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i1 = var_l10;
    var_i2 = var_p2;
    var_i1 += var_i2;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  } else {
    var_i0 = var_p0;
    var_i1 = var_p1;
    var_i2 = var_p2;
    var_i0 = w2c_prog_f19(instance, var_i0, var_i1, var_i2);
    var_l11 = var_i0;
    var_i0 = var_l11;
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 != var_i1;
    if (var_i0) {
      var_i0 = var_l11;
      var_l8 = var_i0;
    }
  }
  var_i0 = var_l8;
  goto var_B0;
  var_i0 = var_l4;
  var_j1 = var_l5;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f13(w2c_prog* instance, u32 var_p0, u32 var_p1, u64 var_p2) {
  u32 var_l3 = 0, var_l4 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0;
  u64 var_l5 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4, var_i7, var_i8, var_i9;
  u64 var_j0, var_j1, var_j5, var_j6, var_j7, var_j9;
  var_i0 = var_p0;
  var_i0 = w2c_prog_f10(instance, var_i0);
  var_l6 = var_i0;
  var_i0 = instance->w2c_g1;
  var_j1 = 8696ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_l7 = var_i0;
  var_j0 = 3ull;
  var_i0 = (u32)(var_j0);
  var_l8 = var_i0;
  var_L3: 
    var_i0 = var_l8;
    var_i1 = var_l7;
    var_i0 = w2c_wasi__snapshot__preview1_fd_prestat_get(instance->w2c_wasi__snapshot__preview1_instance, var_i0, var_i1);
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 == var_i1;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B2;}
    var_i0 = var_l8;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i2 = var_p0;
    var_i3 = var_l6;
    var_i4 = var_p1;
    var_j5 = var_p2;
    var_j6 = 0ull;
    var_j7 = 0ull;
    var_i7 = (u32)(var_j7);
    var_i8 = var_l7;
    var_j9 = 8ull;
    var_i9 = (u32)(var_j9);
    var_i8 += var_i9;
    var_i0 = w2c_wasi__snapshot__preview1_path_open(instance->w2c_wasi__snapshot__preview1_instance, var_i0, var_i1, var_i2, var_i3, var_i4, var_j5, var_j6, var_i7, var_i8);
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_i0 = var_l7;
      var_j1 = 8ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
      goto var_B0;
    }
    var_i0 = var_l8;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l8 = var_i0;
    goto var_L3;
  var_B2:;
  var_j0 = 1ull;
  var_j1 = 18446744073709551615ull;
  var_j0 *= var_j1;
  var_i0 = (u32)(var_j0);
  goto var_B0;
  var_i0 = var_l4;
  var_j1 = var_l5;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_prog_f14(w2c_prog* instance, u32 var_p0, u32 var_p1, u32 var_p2, u32 var_p3, u32 var_p4) {
  u32 var_l5 = 0, var_l6 = 0, var_l8 = 0;
  u64 var_l7 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4;
  u64 var_j1, var_j2, var_j4;
  var_i0 = var_p1;
  var_i1 = var_p2;
  var_i0 = w2c_prog_f21(instance, var_i0, var_i1);
  var_l8 = var_i0;
  var_i0 = var_l8;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = var_p0;
    var_i1 = var_p0;
    var_j2 = 0ull;
    i64_store_default32(&instance->w2c_memory, (u64)(var_i1), var_j2);
    var_i1 = var_p0;
    var_i2 = 8u;
    var_i1 += var_i2;
    var_i2 = var_p3;
    var_i3 = var_p1;
    var_i4 = var_p4;
    var_i2 = w2c_prog_f20(instance, var_i2, var_i3, var_i4);
    var_j2 = (u64)(var_i2);
    i64_store_default32(&instance->w2c_memory, (u64)(var_i1), var_j2);
    var_i1 = var_p0;
    goto var_B0;
  }
  var_i0 = var_p0;
  var_i1 = var_p0;
  var_i2 = var_l8;
  var_i3 = instance->w2c_g1;
  var_j4 = 8684ull;
  var_i4 = (u32)(var_j4);
  var_i3 += var_i4;
  var_i3 = i32_load_default32(&instance->w2c_memory, (u64)(var_i3));
  var_i4 = 1u;
  w2c_prog_f23(instance, var_i1, var_i2, var_i3, var_i4);
  var_i1 = var_p0;
  goto var_B0;
  var_i0 = var_l6;
  var_j1 = var_l7;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
}

void w2c_prog_f15(w2c_prog* instance, u32 var_p0) {
  u32 var_l1 = 0, var_l2 = 0;
  u64 var_l3 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j1;
  var_i0 = 2u;
  var_i1 = var_p0;
  var_i2 = var_p0;
  var_i2 = w2c_prog_f10(instance, var_i2);
  var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
  var_i0 = 1u;
  w2c_wasi__snapshot__preview1_proc_exit(instance->w2c_wasi__snapshot__preview1_instance, var_i0);
  UNREACHABLE;
  var_i0 = var_l2;
  var_j1 = var_l3;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  FUNC_EPILOGUE;
}

void w2c_prog_f16(w2c_prog* instance, u32 var_p0, u64 var_p1, u32 var_p2) {
  u32 var_l3 = 0, var_l4 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, var_l11 = 0, 
      var_l12 = 0;
  u64 var_l5 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j0, var_j1, var_j2, var_j3;
  var_i0 = var_p2;
  var_i1 = var_p0;
  var_j2 = 3ull;
  var_i2 = (u32)(var_j2);
  var_l6 = var_i2;
  var_l7 = var_i1;
  var_i1 = var_l6;
  var_i2 = 32u;
  var_i1 = var_i1 >= var_i2;
  if (var_i1) {
    var_i1 = 5u;
    var_l4 = var_i1;
    var_j1 = 0ull;
    var_l5 = var_j1;
    goto var_B1;
  }
  var_i1 = var_l7;
  var_i2 = var_l6;
  var_i1 <<= (var_i2 & 31);
  var_i0 += var_i1;
  var_l8 = var_i0;
  var_i0 = var_l8;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l9 = var_i0;
  var_i0 = var_l8;
  var_j1 = 4ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l10 = var_i0;
  var_i0 = var_l10;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = 2u;
    var_i1 = var_l9;
    var_i2 = var_l9;
    var_i2 = w2c_prog_f10(instance, var_i2);
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 1u;
    w2c_wasi__snapshot__preview1_proc_exit(instance->w2c_wasi__snapshot__preview1_instance, var_i0);
    UNREACHABLE;
  }
  var_j0 = 2ull;
  var_i0 = (u32)(var_j0);
  var_i1 = var_l9;
  var_i2 = var_l9;
  var_i2 = w2c_prog_f10(instance, var_i2);
  var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
  var_i0 = instance->w2c_g1;
  var_j1 = 8736ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_l11 = var_i0;
  var_i0 = var_l11;
  var_j1 = 31ull;
  var_i1 = (u32)(var_j1);
  var_j2 = var_p1;
  var_i3 = 1u;
  var_i0 = w2c_prog_f24(instance, var_i0, var_i1, var_j2, var_i3);
  var_l12 = var_i0;
  var_j0 = 2ull;
  var_i0 = (u32)(var_j0);
  var_i1 = var_l12;
  var_i2 = var_l11;
  var_j3 = 32ull;
  var_i3 = (u32)(var_j3);
  var_i2 += var_i3;
  var_i3 = var_l12;
  var_i2 -= var_i3;
  var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
  var_i0 = 2u;
  var_i1 = var_l10;
  var_i2 = var_l10;
  var_i2 = w2c_prog_f10(instance, var_i2);
  var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
  var_i0 = 1u;
  w2c_wasi__snapshot__preview1_proc_exit(instance->w2c_wasi__snapshot__preview1_instance, var_i0);
  UNREACHABLE;
  var_B1:;
  var_i0 = var_l4;
  var_j1 = var_l5;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  FUNC_EPILOGUE;
}

u64 w2c_prog_f17(w2c_prog* instance) {
  u32 var_l0 = 0, var_l1 = 0, var_l3 = 0, var_l4 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, 
      var_l9 = 0, var_l10 = 0, var_l11 = 0, var_l12 = 0, var_l13 = 0, var_l14 = 0;
  u64 var_l2 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4, var_i5;
  u64 var_j0, var_j1, var_j2;
  var_i0 = instance->w2c_g0;
  var_i1 = 32u;
  var_i0 -= var_i1;
  var_l0 = var_i0;
  instance->w2c_g0 = var_i0;
  var_i0 = 8258224u;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_i1 = 1000u;
  var_i0 = var_i0 >= var_i1;
  if (var_i0) {
    var_i0 = 6u;
    var_j1 = 0ull;
    var_i2 = 8258156u;
    w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  }
  var_i0 = 8258224u;
  var_i1 = 8258224u;
  var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
  var_i2 = 1u;
  var_i1 += var_i2;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l0;
  var_i1 = var_l0;
  var_i2 = 16u;
  var_i1 += var_i2;
  var_i2 = 8258672u;
  var_i3 = 0u;
  var_i4 = 8257776u;
  var_i5 = 8257624u;
  w2c_prog_f14(instance, var_i1, var_i2, var_i3, var_i4, var_i5);
  var_i1 = var_l0;
  var_i2 = 16u;
  var_i1 += var_i2;
  var_i2 = 16u;
  memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
  var_j0 = 0ull;
  var_i1 = var_l0;
  var_l3 = var_i1;
  var_i1 = var_l3;
  var_j1 = i64_load_default32(&instance->w2c_memory, (u64)(var_i1));
  var_j2 = 0ull;
  var_i1 = var_j1 == var_j2;
  if (var_i1) {
    var_i1 = var_l3;
    var_j1 = i64_load_default32(&instance->w2c_memory, (u64)(var_i1) + 8u);
    var_i1 = (u32)(var_j1);
    var_i2 = 8u;
    var_i1 -= var_i2;
    w2c_prog_f7(instance, var_i1);
  }
  var_i1 = var_l3;
  var_j1 = i64_load_default32(&instance->w2c_memory, (u64)(var_i1));
  var_j2 = 1ull;
  var_i1 = var_j1 == var_j2;
  if (var_i1) {
    var_i1 = var_l3;
    var_j1 = i64_load_default32(&instance->w2c_memory, (u64)(var_i1) + 8u);
    var_i1 = (u32)(var_j1);
    var_l4 = var_i1;
    var_i1 = var_l4;
    var_j1 = i64_load_default32(&instance->w2c_memory, (u64)(var_i1) + 8u);
    var_i1 = (u32)(var_j1);
    var_l5 = var_i1;
    var_i1 = var_l4;
    var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
    var_l6 = var_i1;
    var_i1 = 0u;
    var_l7 = var_i1;
    var_L6: 
      var_i1 = var_l7;
      var_i2 = var_l5;
      var_i1 = var_i1 >= var_i2;
      if (var_i1) {goto var_B5;}
      var_i1 = var_l6;
      var_i2 = var_l7;
      var_i3 = 4u;
      var_i2 *= var_i3;
      var_i1 += var_i2;
      var_l8 = var_i1;
      var_i1 = var_l8;
      var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
      var_i2 = 8u;
      var_i1 -= var_i2;
      w2c_prog_f7(instance, var_i1);
      var_i1 = var_l7;
      var_i2 = 1u;
      var_i1 += var_i2;
      var_l7 = var_i1;
      goto var_L6;
    var_B5:;
    var_i1 = var_l6;
    w2c_prog_f7(instance, var_i1);
    var_i1 = var_l4;
    w2c_prog_f7(instance, var_i1);
  }
  goto var_B1;
  var_i0 = var_l1;
  var_j1 = var_l2;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B1:;
  var_i1 = 8258224u;
  var_i2 = 8258224u;
  var_i2 = i32_load_default32(&instance->w2c_memory, (u64)(var_i2));
  var_i3 = 4294967295u;
  var_i2 += var_i3;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i1), var_i2);
  var_i1 = var_l0;
  var_i2 = 32u;
  var_i1 += var_i2;
  instance->w2c_g0 = var_i1;
  FUNC_EPILOGUE;
  return var_j0;
}

u32 w2c_prog_f18(w2c_prog* instance, u64 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, 
      var_l11 = 0;
  u64 var_l4 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j0, var_j1, var_j2;
  var_j0 = var_p0;
  var_j1 = 2147483648ull;
  var_i0 = var_j0 > var_j1;
  if (var_i0) {
    var_i0 = 8258800u;
    var_l5 = var_i0;
    var_i0 = 2u;
    var_i1 = 8258708u;
    var_i2 = 7u;
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 2u;
    var_i1 = var_l5;
    var_i2 = var_l5;
    var_i3 = 8u;
    var_i2 -= var_i3;
    var_i2 = i32_load_default32(&instance->w2c_memory, (u64)(var_i2));
    var_i0 = w2c_prog_f12(instance, var_i0, var_i1, var_i2);
    var_i0 = 8258724u;
    w2c_prog_f15(instance, var_i0);
    UNREACHABLE;
  }
  var_j0 = var_p0;
  var_j1 = 7ull;
  var_j0 += var_j1;
  var_j1 = 8ull;
  var_j2 = 18446744073709551615ull;
  var_j1 *= var_j2;
  var_j0 &= var_j1;
  var_i0 = (u32)(var_j0);
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_l6 = var_i0;
  var_i0 = var_p1;
  var_j1 = 468ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l7 = var_i0;
  var_i0 = var_p1;
  var_j1 = 472ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
  var_l8 = var_i0;
  var_i0 = var_l7;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_i0 = 1u;
  } else {
    var_i0 = var_l8;
    var_j0 = (u64)(var_i0);
    var_i1 = var_l6;
    var_j1 = (u64)(s64)(s32)(var_i1);
    var_j0 += var_j1;
    var_i1 = var_l7;
    var_j2 = 4ull;
    var_i2 = (u32)(var_j2);
    var_i1 += var_i2;
    var_i1 = i32_load_default32(&instance->w2c_memory, (u64)(var_i1));
    var_j1 = (u64)(var_i1);
    var_i0 = (u64)((s64)var_j0 > (s64)var_j1);
  }
  var_l9 = var_i0;
  var_i0 = var_l9;
  if (var_i0) {
    var_i0 = var_l6;
    var_l10 = var_i0;
    var_i0 = var_l10;
    var_j1 = 4096ull;
    var_i1 = (u32)(var_j1);
    var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
    if (var_i0) {
      var_j0 = 4096ull;
      var_i0 = (u32)(var_j0);
      var_l10 = var_i0;
    }
    var_i0 = var_l10;
    var_j0 = (u64)(s64)(s32)(var_i0);
    var_j1 = 8ull;
    var_j0 += var_j1;
    var_i0 = w2c_prog_f6(instance, var_j0);
    var_l11 = var_i0;
    var_i0 = var_l11;
    var_i1 = var_l7;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l11;
    var_j1 = 4ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i1 = var_l11;
    var_j2 = 8ull;
    var_i2 = (u32)(var_j2);
    var_i1 += var_i2;
    var_i2 = var_l10;
    var_i1 += var_i2;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_p1;
    var_j1 = 468ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i1 = var_l11;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l11;
    var_l7 = var_i0;
    var_i0 = var_l11;
    var_j1 = 8ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l8 = var_i0;
  }
  var_i0 = var_l8;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_p1;
  var_j1 = 472ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_l8;
  var_i2 = var_l6;
  var_i1 += var_i2;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l8;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  goto var_B0;
  var_i0 = var_l3;
  var_j1 = var_l4;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f19(w2c_prog* instance, u32 var_p0, u32 var_p1, u32 var_p2) {
  u32 var_l3 = 0, var_l4 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0;
  u64 var_l5 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3, var_i4;
  u64 var_j0, var_j1, var_j2, var_j4;
  var_i0 = instance->w2c_g1;
  var_j1 = 8696ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_l6 = var_i0;
  var_i0 = var_p1;
  var_l7 = var_i0;
  var_i0 = var_p2;
  var_l8 = var_i0;
  var_L3: 
    var_i0 = var_l8;
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 != var_i1;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B2;}
    var_i0 = var_l6;
    var_i1 = var_l7;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l6;
    var_j1 = 4ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i1 = var_l8;
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_p0;
    var_i1 = var_l6;
    var_j2 = 1ull;
    var_i2 = (u32)(var_j2);
    var_i3 = var_l6;
    var_j4 = 8ull;
    var_i4 = (u32)(var_j4);
    var_i3 += var_i4;
    var_i0 = w2c_wasi__snapshot__preview1_fd_write(instance->w2c_wasi__snapshot__preview1_instance, var_i0, var_i1, var_i2, var_i3);
    var_l9 = var_i0;
    var_i0 = var_l9;
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 != var_i1;
    if (var_i0) {
      var_i0 = var_l9;
      goto var_B0;
    }
    var_i0 = var_l6;
    var_j1 = 8ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l10 = var_i0;
    var_i0 = var_l10;
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_j0 = 1ull;
      var_i0 = (u32)(var_j0);
      goto var_B0;
    }
    var_i0 = var_l7;
    var_i1 = var_l10;
    var_i0 += var_i1;
    var_l7 = var_i0;
    var_i0 = var_l8;
    var_i1 = var_l10;
    var_i0 -= var_i1;
    var_l8 = var_i0;
    goto var_L3;
  var_B2:;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  goto var_B0;
  var_i0 = var_l4;
  var_j1 = var_l5;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f20(w2c_prog* instance, u32 var_p0, u32 var_p1, u32 var_p2) {
  u32 var_l3 = 0, var_l4 = 0, var_l6 = 0, var_l7 = 0;
  u64 var_l5 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j1;
  var_i0 = var_p0;
  var_i1 = var_p1;
  var_i0 = w2c_prog_f9(instance, var_i0, var_i1);
  var_l6 = var_i0;
  var_i0 = var_l6;
  var_i1 = var_p2;
  var_i0 = w2c_prog_f9(instance, var_i0, var_i1);
  var_l7 = var_i0;
  var_i0 = var_l6;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 -= var_i1;
  w2c_prog_f7(instance, var_i0);
  var_i0 = var_l7;
  goto var_B0;
  var_i0 = var_l4;
  var_j1 = var_l5;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f21(w2c_prog* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l5 = 0, var_l6 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, 
      var_l12 = 0, var_l13 = 0, var_l14 = 0, var_l15 = 0, var_l16 = 0, var_l17 = 0, var_l18 = 0, var_l19 = 0, 
      var_l20 = 0, var_l21 = 0, var_l22 = 0, var_l23 = 0;
  u64 var_l4 = 0, var_l11 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i4;
  u64 var_j0, var_j1, var_j2, var_j3;
  var_i0 = instance->w2c_g1;
  var_l5 = var_i0;
  var_i0 = var_p0;
  var_j1 = 2ull;
  var_i1 = (u32)(var_j1);
  var_j2 = 16384ull;
  var_i0 = w2c_prog_f13(instance, var_i0, var_i1, var_j2);
  var_l6 = var_i0;
  var_i0 = var_l6;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = (u32)((s32)var_i0 < (s32)var_i1);
  if (var_i0) {
    var_j0 = 0ull;
    var_i0 = (u32)(var_j0);
    goto var_B0;
  }
  var_j0 = 1024ull;
  var_i0 = (u32)(var_j0);
  var_l7 = var_i0;
  var_i0 = var_l7;
  var_j0 = (u64)(s64)(s32)(var_i0);
  var_i0 = w2c_prog_f6(instance, var_j0);
  var_l8 = var_i0;
  var_j0 = 4096ull;
  var_i0 = w2c_prog_f6(instance, var_j0);
  var_l9 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l10 = var_i0;
  var_j0 = 0ull;
  var_l11 = var_j0;
  var_i0 = var_l5;
  var_j1 = 8696ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_l12 = var_i0;
  var_L4: 
    var_i0 = 1u;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B3;}
    var_i0 = var_l6;
    var_i1 = var_l9;
    var_j2 = 4096ull;
    var_i2 = (u32)(var_j2);
    var_j3 = var_l11;
    var_i4 = var_l12;
    var_i0 = w2c_wasi__snapshot__preview1_fd_readdir(instance->w2c_wasi__snapshot__preview1_instance, var_i0, var_i1, var_i2, var_j3, var_i4);
    var_j1 = 0ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 != var_i1;
    if (var_i0) {
      var_i0 = var_l8;
      w2c_prog_f7(instance, var_i0);
      var_j0 = 0ull;
      var_i0 = (u32)(var_j0);
      var_l8 = var_i0;
      goto var_B3;
    }
    var_i0 = var_l12;
    var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
    var_l13 = var_i0;
    var_j0 = 0ull;
    var_i0 = (u32)(var_j0);
    var_l14 = var_i0;
    var_L7: 
      var_i0 = var_l14;
      var_j1 = 24ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_i1 = var_l13;
      var_i0 = var_i0 <= var_i1;
      var_i0 = !(var_i0);
      if (var_i0) {goto var_B6;}
      var_i0 = var_l9;
      var_i1 = var_l14;
      var_i0 += var_i1;
      var_l15 = var_i0;
      var_i0 = var_l15;
      var_j1 = 16ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
      var_l16 = var_i0;
      var_i0 = var_l16;
      var_i1 = var_l14;
      var_i0 += var_i1;
      var_j1 = 24ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_i1 = var_l13;
      var_i0 = var_i0 > var_i1;
      if (var_i0) {
        goto var_B6;
      }
      var_i0 = var_l15;
      var_j0 = i64_load_default32(&instance->w2c_memory, (u64)(var_i0));
      var_l11 = var_j0;
      var_i0 = var_l15;
      var_j1 = 20ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
      var_l17 = var_i0;
      var_i0 = var_l15;
      var_j1 = 24ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_l18 = var_i0;
      var_i0 = var_l16;
      var_j1 = 2ull;
      var_i1 = (u32)(var_j1);
      var_i0 = var_i0 <= var_i1;
      if (var_i0) {
        var_i0 = var_l18;
        var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
        var_j1 = 46ull;
        var_i1 = (u32)(var_j1);
        var_i2 = 255u;
        var_i1 &= var_i2;
        var_i0 = var_i0 == var_i1;
      } else {
        var_i0 = 0u;
      }
      if (var_i0) {
        var_i0 = var_l18;
        var_i1 = var_l16;
        var_i0 += var_i1;
        var_j1 = 1ull;
        var_i1 = (u32)(var_j1);
        var_i0 -= var_i1;
        var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
        var_j1 = 46ull;
        var_i1 = (u32)(var_j1);
        var_i2 = 255u;
        var_i1 &= var_i2;
        var_i0 = var_i0 == var_i1;
      } else {
        var_i0 = 0u;
      }
      var_l19 = var_i0;
      var_i0 = var_l19;
      var_i0 = !(var_i0);
      if (var_i0) {
        var_i0 = var_l16;
        var_j1 = 3ull;
        var_i1 = (u32)(var_j1);
        var_i0 += var_i1;
        var_i1 = var_l10;
        var_i0 += var_i1;
        var_l20 = var_i0;
        var_i0 = var_l20;
        var_i1 = var_l7;
        var_i0 = var_i0 > var_i1;
        if (var_i0) {
          var_i0 = var_l7;
          var_j1 = 1ull;
          var_i1 = (u32)(var_j1);
          var_l21 = var_i1;
          var_l22 = var_i0;
          var_i0 = var_l21;
          var_i1 = 32u;
          var_i0 = var_i0 >= var_i1;
          if (var_i0) {
            var_i0 = 5u;
            var_l3 = var_i0;
            var_j0 = 0ull;
            var_l4 = var_j0;
            goto var_B1;
          }
          var_i0 = var_l22;
          var_i1 = var_l21;
          var_i0 <<= (var_i1 & 31);
          var_l7 = var_i0;
          var_i0 = var_l7;
          var_i1 = var_l20;
          var_i0 = var_i0 <= var_i1;
          if (var_i0) {
            var_i0 = var_l20;
            var_l7 = var_i0;
          }
          var_i0 = var_l7;
          var_j0 = (u64)(var_i0);
          var_i0 = w2c_prog_f6(instance, var_j0);
          var_l23 = var_i0;
          var_i0 = var_l23;
          var_i1 = var_l8;
          var_i2 = var_l10;
          memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
          var_i0 = var_l8;
          w2c_prog_f7(instance, var_i0);
          var_i0 = var_l23;
          var_l8 = var_i0;
        }
        var_i0 = var_l8;
        var_i1 = var_l10;
        var_i0 += var_i1;
        var_i1 = var_l18;
        var_i2 = var_l16;
        memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
        var_i0 = var_l10;
        var_i1 = var_l16;
        var_i0 += var_i1;
        var_l10 = var_i0;
        var_i0 = var_p1;
        if (var_i0) {
          var_i0 = var_l17;
          var_j1 = 3ull;
          var_i1 = (u32)(var_j1);
          var_i2 = 255u;
          var_i1 &= var_i2;
          var_i0 = var_i0 == var_i1;
        } else {
          var_i0 = 0u;
        }
        if (var_i0) {
          var_i0 = var_l8;
          var_i1 = var_l10;
          var_i0 += var_i1;
          var_j1 = 47ull;
          var_i1 = (u32)(var_j1);
          var_i2 = 255u;
          var_i1 &= var_i2;
          i32_store8_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
          var_i0 = var_l10;
          var_j1 = 1ull;
          var_i1 = (u32)(var_j1);
          var_i0 += var_i1;
          var_l10 = var_i0;
        }
        var_i0 = var_l8;
        var_i1 = var_l10;
        var_i0 += var_i1;
        var_j1 = 10ull;
        var_i1 = (u32)(var_j1);
        var_i2 = 255u;
        var_i1 &= var_i2;
        i32_store8_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
        var_i0 = var_l10;
        var_j1 = 1ull;
        var_i1 = (u32)(var_j1);
        var_i0 += var_i1;
        var_l10 = var_i0;
      }
      var_i0 = var_l14;
      var_j1 = 24ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_i1 = var_l16;
      var_i0 += var_i1;
      var_l14 = var_i0;
      goto var_L7;
    var_B6:;
    var_i0 = var_l13;
    var_j1 = 4096ull;
    var_i1 = (u32)(var_j1);
    var_i0 = var_i0 < var_i1;
    if (var_i0) {
      goto var_B3;
    }
    goto var_L4;
  var_B3:;
  var_i0 = var_l6;
  var_i0 = w2c_wasi__snapshot__preview1_fd_close(instance->w2c_wasi__snapshot__preview1_instance, var_i0);
  var_i0 = var_l9;
  w2c_prog_f7(instance, var_i0);
  var_i0 = var_l8;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = 0ull;
    var_i0 = (u32)(var_j0);
    goto var_B0;
  }
  var_i0 = var_l10;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    var_i0 = var_l10;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 -= var_i1;
    var_l10 = var_i0;
  }
  var_i0 = var_l8;
  var_i1 = var_l10;
  var_i0 += var_i1;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i2 = 255u;
  var_i1 &= var_i2;
  i32_store8_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l5;
  var_j1 = 8684ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_l10;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l8;
  goto var_B0;
  var_B1:;
  var_i0 = var_l3;
  var_j1 = var_l4;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

u32 w2c_prog_f22(w2c_prog* instance, u32 var_p0, u32 var_p1) {
  u32 var_l2 = 0, var_l3 = 0, var_l5 = 0;
  u64 var_l4 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2;
  u64 var_j1;
  var_i0 = var_p1;
  var_i1 = var_p1;
  var_i0 = w2c_prog_f8(instance, var_i0, var_i1);
  var_l5 = var_i0;
  var_i0 = var_l5;
  var_i1 = var_p0;
  var_i2 = var_p1;
  memory_copy(&instance->w2c_memory, &instance->w2c_memory, var_i0, var_i1, var_i2);
  var_i0 = var_l5;
  goto var_B0;
  var_i0 = var_l3;
  var_j1 = var_l4;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_prog_f23(w2c_prog* instance, u32 var_p0, u32 var_p1, u32 var_p2, u32 var_p3) {
  u32 var_l4 = 0, var_l5 = 0, var_l7 = 0, var_l8 = 0, var_l9 = 0, var_l10 = 0, var_l11 = 0, var_l12 = 0, 
      var_l13 = 0, var_l14 = 0, var_l15 = 0, var_l16 = 0, var_l17 = 0;
  u64 var_l6 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j0, var_j1, var_j2;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l7 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l8 = var_i0;
  var_L3: 
    var_i0 = var_l8;
    var_i1 = var_p2;
    var_i0 = var_i0 < var_i1;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B2;}
    var_i0 = var_p1;
    var_i1 = var_l8;
    var_i0 += var_i1;
    var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
    var_j1 = 10ull;
    var_i1 = (u32)(var_j1);
    var_i2 = 255u;
    var_i1 &= var_i2;
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_i0 = var_l7;
      var_j1 = 1ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_l7 = var_i0;
    }
    var_i0 = var_l8;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l8 = var_i0;
    goto var_L3;
  var_B2:;
  var_i0 = var_p2;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    var_i0 = var_l7;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l7 = var_i0;
  }
  var_i0 = var_l7;
  var_l9 = var_i0;
  var_i0 = var_l9;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 == var_i1;
  if (var_i0) {
    var_j0 = 1ull;
    var_i0 = (u32)(var_j0);
    var_l9 = var_i0;
  }
  var_i0 = var_l9;
  var_j0 = (u64)(s64)(s32)(var_i0);
  var_j1 = 4ull;
  var_j0 *= var_j1;
  var_i0 = w2c_prog_f6(instance, var_j0);
  var_l10 = var_i0;
  var_i0 = var_p1;
  var_l11 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l12 = var_i0;
  var_j0 = 0ull;
  var_i0 = (u32)(var_j0);
  var_l8 = var_i0;
  var_L8: 
    var_i0 = var_l8;
    var_i1 = var_p2;
    var_i0 = var_i0 < var_i1;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B7;}
    var_i0 = var_p1;
    var_i1 = var_l8;
    var_i0 += var_i1;
    var_i0 = i32_load8_u_default32(&instance->w2c_memory, (u64)(var_i0));
    var_j1 = 10ull;
    var_i1 = (u32)(var_j1);
    var_i2 = 255u;
    var_i1 &= var_i2;
    var_i0 = var_i0 == var_i1;
    if (var_i0) {
      var_i0 = var_l10;
      var_i1 = var_l12;
      var_j2 = 2ull;
      var_i2 = (u32)(var_j2);
      var_l13 = var_i2;
      var_l14 = var_i1;
      var_i1 = var_l13;
      var_i2 = 32u;
      var_i1 = var_i1 >= var_i2;
      if (var_i1) {
        var_i1 = 5u;
        var_l5 = var_i1;
        var_j1 = 0ull;
        var_l6 = var_j1;
        goto var_B1;
      }
      var_i1 = var_l14;
      var_i2 = var_l13;
      var_i1 <<= (var_i2 & 31);
      var_i0 += var_i1;
      var_i1 = var_l11;
      var_i2 = var_p1;
      var_i3 = var_l8;
      var_i2 += var_i3;
      var_i3 = var_l11;
      var_i2 -= var_i3;
      var_i1 = w2c_prog_f22(instance, var_i1, var_i2);
      i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
      var_i0 = var_l12;
      var_j1 = 1ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_l12 = var_i0;
      var_i0 = var_p1;
      var_i1 = var_l8;
      var_i0 += var_i1;
      var_j1 = 1ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_l11 = var_i0;
    }
    var_i0 = var_l8;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 += var_i1;
    var_l8 = var_i0;
    goto var_L8;
  var_B7:;
  var_i0 = var_p2;
  var_j1 = 0ull;
  var_i1 = (u32)(var_j1);
  var_i0 = var_i0 != var_i1;
  if (var_i0) {
    var_i0 = var_l10;
    var_i1 = var_l12;
    var_j2 = 2ull;
    var_i2 = (u32)(var_j2);
    var_l13 = var_i2;
    var_l14 = var_i1;
    var_i1 = var_l13;
    var_i2 = 32u;
    var_i1 = var_i1 >= var_i2;
    if (var_i1) {
      var_i1 = 5u;
      var_l5 = var_i1;
      var_j1 = 0ull;
      var_l6 = var_j1;
      goto var_B1;
    }
    var_i1 = var_l14;
    var_i2 = var_l13;
    var_i1 <<= (var_i2 & 31);
    var_i0 += var_i1;
    var_i1 = var_l11;
    var_i2 = var_p1;
    var_i3 = var_p2;
    var_i2 += var_i3;
    var_i3 = var_l11;
    var_i2 -= var_i3;
    var_i1 = w2c_prog_f22(instance, var_i1, var_i2);
    i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  }
  var_i0 = var_p3;
  if (var_i0) {
    var_j0 = 1ull;
    var_i0 = (u32)(var_j0);
    var_l8 = var_i0;
    var_L15: 
      var_i0 = var_l8;
      var_i1 = var_l7;
      var_i0 = var_i0 < var_i1;
      var_i0 = !(var_i0);
      if (var_i0) {goto var_B14;}
      var_i0 = var_l10;
      var_i1 = var_l8;
      var_j2 = 2ull;
      var_i2 = (u32)(var_j2);
      var_l13 = var_i2;
      var_l14 = var_i1;
      var_i1 = var_l13;
      var_i2 = 32u;
      var_i1 = var_i1 >= var_i2;
      if (var_i1) {
        var_i1 = 5u;
        var_l5 = var_i1;
        var_j1 = 0ull;
        var_l6 = var_j1;
        goto var_B1;
      }
      var_i1 = var_l14;
      var_i2 = var_l13;
      var_i1 <<= (var_i2 & 31);
      var_i0 += var_i1;
      var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
      var_l15 = var_i0;
      var_i0 = var_l8;
      var_l12 = var_i0;
      var_L18: 
        var_i0 = var_l12;
        var_j1 = 0ull;
        var_i1 = (u32)(var_j1);
        var_i0 = var_i0 != var_i1;
        var_i0 = !(var_i0);
        if (var_i0) {goto var_B17;}
        var_i0 = var_l10;
        var_i1 = var_l12;
        var_j2 = 1ull;
        var_i2 = (u32)(var_j2);
        var_i1 -= var_i2;
        var_j2 = 2ull;
        var_i2 = (u32)(var_j2);
        var_l13 = var_i2;
        var_l14 = var_i1;
        var_i1 = var_l13;
        var_i2 = 32u;
        var_i1 = var_i1 >= var_i2;
        if (var_i1) {
          var_i1 = 5u;
          var_l5 = var_i1;
          var_j1 = 0ull;
          var_l6 = var_j1;
          goto var_B1;
        }
        var_i1 = var_l14;
        var_i2 = var_l13;
        var_i1 <<= (var_i2 & 31);
        var_i0 += var_i1;
        var_i0 = i32_load_default32(&instance->w2c_memory, (u64)(var_i0));
        var_l16 = var_i0;
        var_i0 = var_l16;
        var_i1 = var_l15;
        var_i0 = w2c_prog_f11(instance, var_i0, var_i1);
        var_j1 = 0ull;
        var_i1 = (u32)(var_j1);
        var_i0 = (u32)((s32)var_i0 <= (s32)var_i1);
        if (var_i0) {
          goto var_B17;
        }
        var_i0 = var_l10;
        var_i1 = var_l12;
        var_j2 = 2ull;
        var_i2 = (u32)(var_j2);
        var_l13 = var_i2;
        var_l14 = var_i1;
        var_i1 = var_l13;
        var_i2 = 32u;
        var_i1 = var_i1 >= var_i2;
        if (var_i1) {
          var_i1 = 5u;
          var_l5 = var_i1;
          var_j1 = 0ull;
          var_l6 = var_j1;
          goto var_B1;
        }
        var_i1 = var_l14;
        var_i2 = var_l13;
        var_i1 <<= (var_i2 & 31);
        var_i0 += var_i1;
        var_i1 = var_l16;
        i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
        var_i0 = var_l12;
        var_j1 = 1ull;
        var_i1 = (u32)(var_j1);
        var_i0 -= var_i1;
        var_l12 = var_i0;
        goto var_L18;
      var_B17:;
      var_i0 = var_l10;
      var_i1 = var_l12;
      var_j2 = 2ull;
      var_i2 = (u32)(var_j2);
      var_l13 = var_i2;
      var_l14 = var_i1;
      var_i1 = var_l13;
      var_i2 = 32u;
      var_i1 = var_i1 >= var_i2;
      if (var_i1) {
        var_i1 = 5u;
        var_l5 = var_i1;
        var_j1 = 0ull;
        var_l6 = var_j1;
        goto var_B1;
      }
      var_i1 = var_l14;
      var_i2 = var_l13;
      var_i1 <<= (var_i2 & 31);
      var_i0 += var_i1;
      var_i1 = var_l15;
      i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
      var_i0 = var_l8;
      var_j1 = 1ull;
      var_i1 = (u32)(var_j1);
      var_i0 += var_i1;
      var_l8 = var_i0;
      goto var_L15;
    var_B14:;
  }
  var_i0 = var_p1;
  w2c_prog_f7(instance, var_i0);
  var_j0 = 24ull;
  var_i0 = w2c_prog_f6(instance, var_j0);
  var_l17 = var_i0;
  var_i0 = var_l17;
  var_i1 = var_l10;
  i32_store_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
  var_i0 = var_l17;
  var_j1 = 8ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_l7;
  var_j1 = (u64)(var_i1);
  i64_store_default32(&instance->w2c_memory, (u64)(var_i0), var_j1);
  var_i0 = var_l17;
  var_j1 = 16ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  var_i1 = var_l7;
  var_j1 = (u64)(var_i1);
  i64_store_default32(&instance->w2c_memory, (u64)(var_i0), var_j1);
  var_i0 = var_p0;
  var_i1 = var_p0;
  var_j2 = 1ull;
  i64_store_default32(&instance->w2c_memory, (u64)(var_i1), var_j2);
  var_i1 = var_p0;
  var_i2 = 8u;
  var_i1 += var_i2;
  var_i2 = var_l17;
  var_j2 = (u64)(var_i2);
  i64_store_default32(&instance->w2c_memory, (u64)(var_i1), var_j2);
  var_i1 = var_p0;
  goto var_B0;
  var_B1:;
  var_i0 = var_l5;
  var_j1 = var_l6;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
}

u32 w2c_prog_f24(w2c_prog* instance, u32 var_p0, u32 var_p1, u64 var_p2, u32 var_p3) {
  u32 var_l4 = 0, var_l5 = 0, var_l8 = 0, var_l9 = 0;
  u64 var_l6 = 0, var_l7 = 0, var_l10 = 0, var_l11 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j0, var_j1, var_j2;
  var_j0 = var_p2;
  var_l7 = var_j0;
  var_i0 = var_p3;
  if (var_i0) {
    var_j0 = var_p2;
    var_j1 = 0ull;
    var_i0 = (u64)((s64)var_j0 < (s64)var_j1);
  } else {
    var_i0 = 0u;
  }
  var_l8 = var_i0;
  var_i0 = var_l8;
  if (var_i0) {
    var_j0 = 0ull;
    var_j1 = var_l7;
    var_j0 -= var_j1;
    var_l7 = var_j0;
  }
  var_i0 = var_p1;
  var_l9 = var_i0;
  var_L5: 
    var_i0 = 1u;
    var_i0 = !(var_i0);
    if (var_i0) {goto var_B4;}
    var_i0 = var_p0;
    var_i1 = var_l9;
    var_i0 += var_i1;
    var_j1 = var_l7;
    var_j2 = 10ull;
    var_l10 = var_j2;
    var_l11 = var_j1;
    var_j1 = var_l10;
    var_i1 = !(var_j1);
    if (var_i1) {
      var_i1 = 3u;
      var_l5 = var_i1;
      var_j1 = 0ull;
      var_l6 = var_j1;
      goto var_B1;
    }
    var_j1 = var_l11;
    var_j2 = var_l10;
    var_j1 = REM_U(var_j1, var_j2);
    var_i1 = (u32)(var_j1);
    var_i2 = 255u;
    var_i1 &= var_i2;
    var_j2 = 48ull;
    var_i2 = (u32)(var_j2);
    var_i3 = 255u;
    var_i2 &= var_i3;
    var_i1 += var_i2;
    var_i2 = 255u;
    var_i1 &= var_i2;
    i32_store8_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_j0 = var_l7;
    var_j1 = 10ull;
    var_l10 = var_j1;
    var_l11 = var_j0;
    var_j0 = var_l10;
    var_i0 = !(var_j0);
    if (var_i0) {
      var_i0 = 2u;
      var_l5 = var_i0;
      var_j0 = 0ull;
      var_l6 = var_j0;
      goto var_B1;
    }
    var_j0 = var_l11;
    var_j1 = var_l10;
    var_j0 = DIV_U(var_j0, var_j1);
    var_l7 = var_j0;
    var_i0 = var_l9;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 -= var_i1;
    var_l9 = var_i0;
    var_j0 = var_l7;
    var_j1 = 0ull;
    var_i0 = var_j0 == var_j1;
    if (var_i0) {
      goto var_B4;
    }
    goto var_L5;
  var_B4:;
  var_i0 = var_l8;
  if (var_i0) {
    var_i0 = var_p0;
    var_i1 = var_l9;
    var_i0 += var_i1;
    var_j1 = 45ull;
    var_i1 = (u32)(var_j1);
    var_i2 = 255u;
    var_i1 &= var_i2;
    i32_store8_default32(&instance->w2c_memory, (u64)(var_i0), var_i1);
    var_i0 = var_l9;
    var_j1 = 1ull;
    var_i1 = (u32)(var_j1);
    var_i0 -= var_i1;
    var_l9 = var_i0;
  }
  var_i0 = var_p0;
  var_i1 = var_l9;
  var_i0 += var_i1;
  var_j1 = 1ull;
  var_i1 = (u32)(var_j1);
  var_i0 += var_i1;
  goto var_B0;
  var_B1:;
  var_i0 = var_l5;
  var_j1 = var_l6;
  var_i2 = 8258156u;
  w2c_prog_f16(instance, var_i0, var_j1, var_i2);
  UNREACHABLE;
  var_B0:;
  FUNC_EPILOGUE;
  return var_i0;
}

void w2c_prog_0x5Fstart_0(w2c_prog* instance) {
  u32 var_l0 = 0;
  FUNC_PROLOGUE;
  u32 var_i0, var_i1, var_i2, var_i3;
  u64 var_j0, var_j1;
  var_j0 = w2c_prog_f17(instance);
  var_i1 = 2u;
  var_i2 = 0u;
  var_i3 = 0u;
  var_i1 = w2c_prog_f12(instance, var_i1, var_i2, var_i3);
  var_j1 = 255ull;
  var_j0 &= var_j1;
  var_i0 = (u32)(var_j0);
  w2c_wasi__snapshot__preview1_proc_exit(instance->w2c_wasi__snapshot__preview1_instance, var_i0);
  FUNC_EPILOGUE;
}
