/* Automatically generated by wasm2c */
#ifndef VYRN_LISTDIR_22040_W2C_H_GENERATED_
#define VYRN_LISTDIR_22040_W2C_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_wasi__snapshot__preview1;

typedef struct w2c_prog {
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  wasm_rt_memory_t w2c_memory;
} w2c_prog;

void wasm2c_prog_instantiate(w2c_prog*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_prog_free(w2c_prog*);
wasm_rt_func_type_t wasm2c_prog_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'wasi_snapshot_preview1' 'fd_close' */
u32 w2c_wasi__snapshot__preview1_fd_close(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_prestat_get' */
u32 w2c_wasi__snapshot__preview1_fd_prestat_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_readdir' */
u32 w2c_wasi__snapshot__preview1_fd_readdir(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u64, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'path_open' */
u32 w2c_wasi__snapshot__preview1_path_open(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32, u32, u64, u64, u32, u32);

/* import: 'wasi_snapshot_preview1' 'proc_exit' */
void w2c_wasi__snapshot__preview1_proc_exit(struct w2c_wasi__snapshot__preview1*, u32);

/* export: '_start' */
void w2c_prog_0x5Fstart(w2c_prog*);

/* export: 'memory' */
wasm_rt_memory_t* w2c_prog_memory(w2c_prog* instance);

#ifdef __cplusplus
}
#endif

#endif  /* VYRN_LISTDIR_22040_W2C_H_GENERATED_ */
